### ISSUE TITLE
Crash when adding a new user filter rule

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#1013]
See here:
https://github.com/AdguardTeam/AdguardForiOS/issues/843#issuecomment-494987581

**Comment by Superkloton** [comment]
iOS 11.3.1, iPhone X 64 GB

**Comment by ameshkov** [comment]
@Superkloton could you please check build 135, do you still experience that crash?

**Comment by Superkloton** [comment]
Yes, problem persists.

**Comment by Superkloton** [comment]
OK figured it out with a .txt file which I then could import.

**Comment by ameshkov** [comment]
> It works, but if I try adding several at once it crashes. How can I add my own filters? I have several hundreds, i can't just copy and paste them one by one...

Hmm, this one is good.

@IvanIin we should handle line break characters and add multiple rules.

**Comment by Superkloton** [comment]
AdGuard still has problems with user filters. When I add new user filters I often get the following problems:

- Error message "Filters can’t be loaded into Safari. The last changes could not have been applied because of that." Filter is displayed in the user filter list for a short time and then disappears again.
- AdGuard crashes when I try to edit filters
- Deleted user filters reappear again after a few seconds
- Imports are reverted after a few seconds and the old filters are back again

When I restart Safari and AdGuard, it works without any problems for a while until it starts again. Really weird.

Oh by the way, the "Search" button in the user filter list is difficult to hit. You actually have to tap to
 the left of the button on the iPhone X. If you tap directly on it, nothing happens.

iPhone X, iOS 12.3, AdGuard 3.0.0(141)

![IMG_0050](https://user-images.githubusercontent.com/22617697/59968113-8133bb80-9534-11e9-98f4-5ceccb7ff608.png)
