### ISSUE TITLE
iOS Beta 3 - Custom Filters

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdguardForiOS#1048]
### Steps to reproduce
Installed Custom Filters from https://github.com/BlackJack8/iOSAdblockList
- EasyListFormat.txt
- Miscellaneous (EasyListFormat)

### Expected behavior
Operating normally

### Actual behavior
No internet access
It seems there are a limitation of the number of rules but I cannot figure out which one it is.
- EasyListFormat.txt Filter with 3378 rules works
- Miscellaneous (EasyListFormat) Filter with 8128 rules does not work.

Strange because on iOS Adguard Pro, it works like a charm with both filters activated.

###User ID**: 2219646
**Subject**: Beta Tester

### Your environment

* iPhone XS Max
*  iOS 12.3.1 
*  iOS 12.3.1 Safari
* Wi-fi and  mobile internet connection

**Comment by ameshkov** [comment]
We will try to reproduce this on our side, thanks for reporting it!

**Comment by Quorum75** [comment]
@Ameshkov Did you reproduce it?

**Comment by ameshkov** [comment]
@Quorum75 sorry for the delay!

The problem is in this filter list: https://github.com/BlackJack8/iOSAdblockList/blob/master/Miscellaneous%20(EasyListFormat)

It contains a problematic rule: `||^` that blocks ALL requests.

We'll fix this on our side in v3.1 when we start using the same rules converter as AdGuard for Safari uses.

**Comment by Quorum75** [comment]
Thank you!
