### ISSUE TITLE
Splash Screen still white

### ISSUE THREAD

**Issue by PentagramTr** [AdguardTeam/AdguardForiOS#1061]
Please apply dark mode to the splash screen as in Adguard Pro.

<details><summary>Screenshot:</summary>

![PICSEW_3FC3](https://user-images.githubusercontent.com/34379403/59296396-8cfac480-8c8e-11e9-9eae-3fcd43c412e0.png)

</details>

### Your environment

* Device model and storage size: iPhone 5s 16 GB
* Operating system and version: iOS 12.3.1
* Browser: Safari
* Wi-fi
* AdGuard Premium

**Comment by Yuan573** [comment]
I remember this is because the new AdGuard default theme is white, and Apple doesn't allow developers to change launch screen. 
But maybe AdGuard Term has another solution.

https://stackoverflow.com/questions/38521503/ios-launch-screen-for-app-with-different-themes
https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/launch-screen/

**Comment by 08kovalchuk03** [comment]
It is impossible to change LaunchScreen, cause it doesn't execute any code
I've tried different hacks, like making ContainerView with embed in navigationController, but even init isn't called
