### ISSUE TITLE
Add "automatic" theme

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#1084]
We should maintain three themes:
1. Light
2. Dark
3. Automatic -- depends on the OS global theme

**Comment by worldsdream** [comment]
I like that. 

It would also be nice if it would change by brightness selection. 

For example: when your brightness dims, it will become dark. When it brights up it will be white.

You also give us a time selection. 
For example: from 08:00 till 22:00 it will show us the light theme. Otherwise it will show us the white theme. 

Both of the features are already implemented by other applications.

**Comment by ameshkov** [comment]
> Both of the features are already implemented by other applications.

Could you please give a couple of examples?

**Comment by worldsdream** [comment]
@ameshkov

Tweetbot application has the feature that it will adapt to your brightness. You can set it up in settings. You can also manually change from light and dark theme with 2 finger vertical swipe in the application. 

Nu.nl application has in the settings section a timer based. You can setup which time to time for a dark theme. It will switch at those times. 

I prefer tweetbot style. That is the best ever.

**Comment by AlikhanAliev** [comment]
https://share.goabstract.com/f634f9d6-e340-417b-bcb5-26316fad3316
