### ISSUE TITLE
No longer open-source?

### ISSUE THREAD

**Issue by brianclinkenbeard** [AdguardTeam/AdguardForiOS#1085]
There has been no updates to the code in about a year, even though the app continues to be updated. Is the app no longer open source? Perhaps the README should be updated.

**Comment by planet0** [comment]
According to their most recent update on the App Store, they have continued to mention: "**AdGuard for iOS is an open source app, it’s totally transparent and safe to use.**"

I think they just haven't gotten around to publishing the new changes to GitHub since the previous update last year during the whole Apple Guidelines fiasco.

@ameshkov?

**Comment by ameshkov** [comment]
We'll push the updated code a little bit later. I'd like to keep it in v2.X state until the Pro update passes (or not) the review just in case.

**Comment by superlex** [comment]
Sources updated, thanks :)
