### ISSUE TITLE
Redesign filters list - it is not obvious how to get to filter details now

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#11]
Report from a beta tester:

> - UI: Actually, I needed to watch the Quick Tour twice to find out that I can tap on a filter to get Details to it. I think there should be a visual hint for that. At first, a chevron on the right end of each filter came to my mind, but I can't remember if I've ever seen a combination of an on/off-toggle with a chevron. Then the blue (i) came to my mind (like at the wifi settings), but actually I don't like the look of that symbol. May be a simple text below the search bar: "tap on a filter to get more information"?

**Comment by dartrax** [comment]
I think the problem is not the image in the quick tour.
Rather it is the fact that there is no visual hint that you can tap on a filter row right there in the filters section. So, if you forget what the quick tour told you (which is not unusual for a settings tool that is not opened that often) than you might never discover that feature - or only when mistakenly tapping on a filter.
So a better image in the quick tour wouldn't change that.
- dartrax

PS: I was that beta tester :-)

**Comment by ameshkov** [comment]
@dartrax you are right, we should somehow show user that filter is selectable.

But I can't yet remember any standard iOS way to do this.
Have you ever seen something like this in other iOS apps?

**Comment by dartrax** [comment]
I can't remember a standard way, too. For me, a natural way would be a chevron > behind the toggle, like that:
[ Filtername (I/O) > ]
But I've never seen that. And I think if it can be done easily, one would certainly already have seen it ;-)
I only can remember the complicated way Apple took with notification center settings in earlier Version of iOS: They splitted the list of possible notifications in an activated section and in an deactivated section. You could tap into each item to get to the details, or by tapping "edit" you could move the items from one list to another. (Nowadays, they removed the option to control the notifications in the overview list, you have to step into each item to set in on or off - even worse)
But that would make the filter list more complicated than it should be.
The simplest thing that I can think of is a short text hint like "tap on a filter to get more information" above or below the filter list.

**Comment by ameshkov** [comment]
Simple solution is to replace on-off switch with it's current status and a chevron.
Something like:
English filter    *On*   >

Switching filter status takes time so additional tap to get to the filter details might be not that bad.

**Comment by dartrax** [comment]
That's true. May be that is the best Way to do it.
There is also the possibility to impement a swipe-to-activate/deactivate in the filters list.

**Comment by ameshkov** [comment]
> There is also the possibility to impement a swipe-to-activate/deactivate in the filters list.

Great idea, thank you!

**Comment by Stillness-2** [comment]
Something like this: 
![tipa](https://cloud.githubusercontent.com/assets/12689/10816063/21da9aa4-7e41-11e5-9a52-8e51edbefc58.png)

**Comment by dartrax** [comment]
Excellent! Now it's clear that you can tap to get more details.
Will there be a quick way to change status? Like tapping on the checkmark or swiping?

**Comment by Stillness-2** [comment]
> Will there be a quick way to change status? Like tapping on the checkmark or swiping?

No, we decided not to do it.

**Comment by ameshkov** [comment]
@dartrax not to do it right now:) 

I just think it's really not obvious for user, don't you think?

**Comment by dartrax** [comment]
You are right, it would be not obvious. I'm still glad that you choosed to place the > signs at the end of each entry rather than a toggle, because for new users it's more important to know where to get more information about each filter than to know where to turn it on and off quickly.

One more thing: Turning it on and off quickly wouldn't work that way nevertheless, since the app (or the OS) needs too much time to load the changed set of filters. It would not be possible to work through the filters list as fast as you read the filter names and swipe them to toggle just how you need them.

So - with that in mind, it might be nice to have an edit mode. Like: have an "edit"-Button in the upper right (making that feature obvious), tap it, have all the > signs replaced with a toggle, work fast through the filter list toggling them as needed, tap "done", and wait until the new filter set is loaded.

That way, you can first concentrate on customizing the filter list without constantly being interrupted by the app loading filters, and give the app time to load the filters when you are done.

**Comment by ameshkov** [comment]
Huh, Edit mode is really great idea, thank you!
