### ISSUE TITLE
AG for iOS v3.x <> AG Pro for iOS

### ISSUE THREAD

**Issue by YBS-PC** [AdguardTeam/AdguardForiOS#1308]
lancelot-moon commented #1307 
> AG for iOS and AG Pro for iOS will be almost the same in v3.x if Apple approves their updates.AG Pro for iOS v3 = AG for iOS v3 + Premium features.(Just you may not need to do in-app purchasing in the future AG Pro for iOS v3 for Premium features.)
> --
I think there is some differences
AG Pro for iOS has the option to add filters (antitracking) where you can add for example adguard base & mobile filter and it will block all ads in ios applications, it is not necessary to use the AdguardDNS. But AG for iOS v3.x with premium features blocks ads in IOS apps only if you use AdguardDNS

**Comment by lancelot-moon** [comment]
You're absolutely wrong.
AdGuard Base & Mobile ads filter belong to Safari content blocker and don't block all ads in iOS apps.

Adding them in DNS filters subscription doesn't make sense because of being unsupported.

It's obvious that you don't know AG for iOS will have the features of blacklist, whitelist and DNS filters subscription in v3.2 or v3.3.

Now, AG Pro for iOS is v2.1.2.
If AG for iOS v3.2 can be approved by Apple, I guess AdGuard team will submit AG Pro for iOS v3.2 later.

**Comment by YBS-PC** [comment]
> Adding them in DNS filters subscription doesn't make sense because of being unsupported.

Maybe I'm wrong. But I have both AG pro and AGios+premium. And when I added to the antitracking lists (not filters, but antitracking) a list of AG base and mobile rules and specified google as the DNS, in the applications I use advertising disappeared (for example, in chrome on the site https://checkadblock.ru  some ads are blocked). At the same time in logs I see that some links are blocked by these lists of filters. 
I don't use safari at all.
And in AG ios + premium advertising disappears only if you specify AdGuardDNS

**Comment by SoLenny** [comment]
@YBS-PC @lancelot-moon Hello, guys.
Adguard Pro version is now more functional than the free version with premium functions.
Now we are working on version 3.2 of the free application, which will be very close in functionality to the pro version. Maybe at this stage we will release a new version of AdGuard Pro.
