### ISSUE TITLE
"VPN Detected" - Hotstar app

### ISSUE THREAD

**Issue by specter78** [AdguardTeam/AdguardForiOS#1515]
Adguard v4.0.0 (381)
Hotstar v8.06

Hotstar is able to detect Adguard vpn and refuses to launch until vpn is disabled.

![Hotstar](https://user-images.githubusercontent.com/40606342/76429220-bc349280-63d4-11ea-92b9-bbb0f9a7ad6c.jpg)

**Comment by lancelot-moon** [comment]
VPN Unlimited is so, too.
Such VPN apps provide different protocols for VPN.
They use personal VPN or VPN configuration according to what protocol you choose.
That's why they'll detect if there are other active VPN apps, like AdGuard.

Run your VPN first and then run AdGuard.
Otherwise, tell your VPN provider to improve its app (detect if there are other active VPN apps when you choose to use the VPN protocol in VPN configuration).

**Comment by SoLenny** [comment]
@specter78 @lancelot-moon Hello, guys.
Unfortunately we can’t do anything about it. Prevent applications from detecting VPN usage is not in our power.

**Comment by specter78** [comment]
Hotstar is a video streaming platform and not an vpn app.

**Comment by SoLenny** [comment]
@specter78 I understood. But we can’t make it so applications cannot detect that you are using our VPN.

**Comment by lancelot-moon** [comment]
It's not AdGuard's business.
@specter78 should go to contact Hotstar's customer support.
