### ISSUE TITLE
"Tracking Protection" does not automatically turn off

### ISSUE THREAD

**Issue by bigdargon** [AdguardTeam/AdguardForiOS#1516]
### Issue Details

- **AdGuard version:**
  - AdGuard for iOS v4.0.0 (396)
- **Device model and storage size:**
  - iPhone 8 Plus
- **Operating system and version:**
  - 13.3.1

### Expected Behavior

The application automatically turns off "Tracking protection" when turning on the VPN of another application

### Actual Behavior

The application still detects that "Tracking Protection" is turned on, even though it is using another application's VPN

### Steps to reproduce

1. Turn on the VPN of any other application (Example: Cloudflare, Adguard Pro, ...)
2. "Tracking Protection" continues to turn on

### Video

https://www.youtube.com/watch?v=GSjVUFOZy10

**Comment by zznosar** [comment]
It’s probably because its waiting for the other VPN to be disconnected. it’s like its in Waiting State.

Other VPN apps are like that if their configuration falls under Personal VPN section. They don’t automatically disable. They are waiting because they are On Demand.

I could be wrong though. Its just my observation.

**Comment by bigdargon** [comment]
@zznosar build 390 does not appear this error
