### ISSUE TITLE
Can’t add custom filter

### ISSUE THREAD

**Issue by StoreksFeed** [AdguardTeam/AdguardForiOS#1621]
### Device
- AdGuard for iOS v4.0.1 (495)
- iPhone SE 1 64gb
- iOS 14.0 (18A5342e)

### Expected Behavior

After I enter the URL to create custom filter I expected to see some browser with possibility to select an object to block

### Actual Behavior

No browser was opened but an error occurred

### Screenshots

![C080594A-31EB-43FC-815D-DCD874321E38](https://user-images.githubusercontent.com/28383692/90241619-e2a79f80-de44-11ea-9962-adbb8a5778e0.png)

### Additional Information

I will try to reproduce this error on other device and I will report the result here

**Comment by StoreksFeed** [comment]
iPhone X 64gb, iOS 13.6 (17G68)
Same issue

**Comment by Maxim-Butov** [comment]
This function has a otherwise purpose. It allows you to add an existing filter with a lot of rules in text format.
If you want to block some element on a specific site yourself, use the safari addguard assistant (I attach a screenshot). It will automatically create a custom rule which you can see under Settings -> Safari Protection -> User Rules.
Anyway, please use the report tool https://reports.adguard.com/ to block missed ads, we will add them to our standard filters.
![IMG_17EF76498473-1(1)](https://user-images.githubusercontent.com/67098694/90386740-aca92c00-e08d-11ea-89e1-9bad2eed05d4.jpg)
