### ISSUE TITLE
AdGuard Pro for IOS Be invalid

### ISSUE THREAD

**Issue by EricMzky** [AdguardTeam/AdguardForiOS#1820]
1. After downloading the Pro version, open the 6 options of content blocker in Safari, then open the software and turn on the switch

2. Then browse related URLs to search for related information through Safari, but found that the interception of advertisements failed, and in the Pro software, I saw the request on the homepage, encrypted, and the average time was 0.

AdGuard Pro 4.2.1
IOS 14.8
Safari Protection ON
DNS Protection OFF
Safari Interceptor ON

**Comment by EricMzky** [comment]
Photo there ![image](https://user-images.githubusercontent.com/37823382/133355897-26d42586-536a-4b92-beaf-daaf60f4ea59.png)

**Comment by Aydinv13** [comment]
@EricMzky this counter which includes `requests`, `encrypted` and `avg. time` is related to DNS module. It starts tracking when you enable DNS but it doesn't go for Native DNS.

**Comment by EricMzky** [comment]
> @EricMzky this counter which includes `requests`, `encrypted` and `avg. time` is related to DNS module. It starts tracking when you enable DNS but it doesn't go for Native DNS.

But I found that I don't open the dns service now. He still has many advertising animation porn links that have not been successfully blocked.![image](https://user-images.githubusercontent.com/37823382/133561643-fe25bf30-0e8f-4530-bdd8-554d7b3351ee.png)

**Comment by Aydinv13** [comment]
@EricMzky ok, what 6 options did you enable?

**Comment by EricMzky** [comment]
> @EricMzky ok, what 6 options did you enable?

look here ![image](https://user-images.githubusercontent.com/37823382/133574222-5855af32-3bea-43db-8d3b-d7af8f4bb6ee.png)![image](https://user-images.githubusercontent.com/37823382/133574285-d5cc00a9-8037-48ef-90fc-254389d426d4.png)

**Comment by EricMzky** [comment]
Does anyone support it? thanks

**Comment by Aydinv13** [comment]
@EricMzky sorry for delay
To troubleshoot this issue, we need to get the app logs.
Here's what we need you to do:
1. Open Settings --> General --> Turn **Advanced mode** on --> Advanced settings --> Turn **Debug logs** switch on;
2. Reproduce the issue and remember the exact time when it happened;
3. Disable "DNS Privacy";
4. Open the settings --> Support --> **Export logs**;
4. System popup will be opened --> Choose "Mail" app
5. Enter `apple@adguard.com` as a recipient;
6. Mention this issue number in the subject and add the time the issue was reproduced at.

**Comment by Aydinv13** [comment]
Closed due to no reply. Reopen if needed please
