### ISSUE TITLE
Adguard IOS taking a long time to refresh filter lists

### ISSUE THREAD

**Issue by Birbber** [AdguardTeam/AdguardForiOS#1844]
@jimmysofat6864 commented on [Tue Nov 23 2021](https://github.com/AdguardTeam/AdGuardForSafari/issues/666)

I'm not sure what the problem is but for some reason on all my devices it is taking a really long time to refresh or add filters in AdGuard for IOS. I am on the latest IOS version and the latest AdGuard version but I still have this issue. Adguard seems to refresh filters a lot faster in the extension or on my Mac but takes like about 10 minutes on my iPhone.

**Comment by AleksandrShulgin** [comment]
@jimmysofat6864
The fact is that due to Apple's policy, the syntax in our filters is not supported on iOS, so when updating/adding filters, they are converted into a syntax that is understandable for iOS.

Considering that in iOS 15 the size of content blockers has been increased from 50K to 150K, most likely you have a large number of filters enabled, which is why it takes so much time.
