### ISSUE TITLE
Go to my account > Error 404

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForiOS#2004]
1. Open AdGuard
2. Navigate to Settings > License
3. Tap Go to my account
4. A new tab in Safari will open to [this link](https://auth.adguard.com/oauth/authorize?response_type=code&client_id=adguard-website&redirect_uri=https%3A%2F%2Fmy.adguard.com%2Foauth%2Fcallback.html&scope=trust&locale=en&state=https%3A%2F%2Fmy.adguard.com%2Fen%2Fmain.html%3Futm_campaign%3Daccount%26utm_medium%3Dlicense%26utm_source%3Dios&reg_source=ADBLOCK), which 404's

https://user-images.githubusercontent.com/95468948/173448220-4cf8f544-efb5-429c-aabc-c7f59883b647.MOV

**Comment by Versty** [comment]
Thanks for your report, @gGkAC3qfszbdViFkw4Fk9ooS2u!
We tried to reproduce this issue on our devices but it works fine. 
Thats why to troubleshoot unusual behaviour we would like to get the app logs from your device.
Please follow the steps above to help us resolve this issue:

1. Open Settings --> General --> Turn Advanced mode on --> Advanced settings --> Turn Debug logs switch on;
2. Reproduce the issue and remember the exact time when it happened;
3. Open the settings --> Support --> Export logs;
4. System popup will be opened --> Choose "Mail" app;
5. Enter apple@adguard.com as a recipient;
6. Mention this issue number in the subject and add the time the issue was reproduced at.
