### ISSUE TITLE
DNS filtering stops working after a period of time

### ISSUE THREAD

**Issue by Emtp563** [AdguardTeam/AdguardForiOS#2056]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ x] I am running the latest version
- [ x] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

DNS filtering stops working after a period of inactivity. The only way to re enable is to go to settings/advanced/low level settings/switch tunnel mode Tunnel mode doesn’t switch automatically, a re-boot is needed.

Adguard version 4.4.3(961)
IPadOS 16.1 (20BS027f)

- **AdGuard version:**
  - 
- **Device model and storage size:**
  - 
- **Operating system and version:**
  - 
- **Browser or App:**
  - 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by Versty** [comment]
@Emtp563 Hi! This issue might be caused by the new iOS 16 beta version. 
How long should be the period of inactivity ?

Also, could you collect logs and send to our devs?

1. Open Settings --> General --> Turn **Advanced mode** on --> Advanced settings --> Turn **Debug logs** switch on;
2. Reproduce the issue and remember the exact time when it happened;
3. Open the settings --> Support --> **Export logs**;
4. System popup will be opened --> Choose "Mail" app
5. Enter `apple@adguard.com` as a recipient;
6. Mention this issue number in the subject and add the time the issue was reproduced at.

**Comment by Versty** [comment]
@Emtp563 May I ask you to collect logs one more time? 
We have examined your logs and realised that it contains too much info for this case. Without knowing exact time of the issue, it is almost impossible to find proper lines in the logs. 

- So, please, turn **Debug logs** switch **off**
- Open the **Protection** tab -> **DNS Protection** -> **DNS server**-> Tap on the already selected server -> Change server Protocol to **Regular**

Then repeat all the steps from the comment above.

**Comment by F3000** [comment]
I have seen this on my iPad mini with iOS 16 too .

Can't connect to Wi-Fi until a) device restarts or b)turn of DNS filtering

**Comment by Versty** [comment]
@F3000 @Emtp563 
Does the issue still persist? 
Please send logs if so.

**Comment by Versty** [comment]
@Emtp563 Closed due to inactivity. 
Please reopen if needed.
