### ISSUE TITLE
The app can't update the ads block list

### ISSUE THREAD

**Issue by SnIPeRSnIPeR** [AdguardTeam/AdguardForiOS#2069]
iOS 14.8, AdGuard 4.4.4

The app can't update the ads block list. Ads on websites are not blocked.

[image](https://user-images.githubusercontent.com/31162059/197380101-e60662d7-2e74-4e51-a62e-0598b1d28dd4.png)

![image](https://user-images.githubusercontent.com/31162059/197380247-2c33e82c-122f-4052-a788-1e4fed4b98e3.png)

**Comment by Versty** [comment]
@SnIPeRSnIPeR Hi! 
Please, follow the path **Settings -> Safari -> Extensions**  and make sure all content blockers provided by AdGuard are enabled.
If so, re-enable and try to update in-app filters again.

**Comment by SnIPeRSnIPeR** [comment]
> @SnIPeRSnIPeR Hi! 
> Please, follow the path **Settings -> Safari -> Extensions**  and make sure all content blockers provided by AdGuard are enabled.
> If so, re-enable and try to update in-app filters again. 
> 

Doesn't work..

**Comment by Versty** [comment]
@SnIPeRSnIPeR 
Could you please collect logs from your device? 

1. Open Settings --> General --> Turn **Advanced mode** on --> Advanced settings --> Turn **Debug logs** switch on;
2. Reproduce the issue and remember the exact time when it happened;
3. Open the settings --> Support --> **Export logs**;
4. System popup will be opened --> Choose "Mail" app
5. Enter `apple@adguard.com` as a recipient;
6. Mention this issue number in the subject and add the time the issue was reproduced at.

**Comment by Versty** [comment]
@SnIPeRSnIPeR any updates?

**Comment by SnIPeRSnIPeR** [comment]
Yes.

**Comment by Versty** [comment]
@SnIPeRSnIPeR It may help if you try to update filter lists with vpn enabled. 
Also keep in mind that only enabled filter lists will be updated.

**Comment by Versty** [comment]
@SnIPeRSnIPeR Unfortunately, I can't find any logs with the issue number `2069`, could you resend it please?

**Comment by Versty** [comment]
@SnIPeRSnIPeR Any good news?

**Comment by Versty** [comment]
@SnIPeRSnIPeR Closed due to inactivity. 
Please reopen if needed.

**Comment by SnIPeRSnIPeR** [comment]
Can't update again. What's going on??
