### ISSUE TITLE
Safari native iOs - Ultra slow with AdGuard pro

### ISSUE THREAD

**Issue by preferredindifferent** [AdguardTeam/AdguardForiOS#2083]
Hi,
I purchased AdGuard pro two days ago and ever since my safari on iOs is unbearably slow. Even if disabling all filters but the 3 Ad blocking lists and Ad guard. Tracking Protection, Safari is not usable at all. This also affects local access (i.e. accessing a pi via IP within a network that is excluded from AdGuard pro). Is this a known issue

**Comment by Versty** [comment]
@xdemiansmithx Hi! 
If you disable dns protection, would it be slow then?

**Comment by Versty** [comment]
@xdemiansmithx Please disable Safari protection and enable DNS protection and let me know the result.

**Comment by xdemiansmithx** [comment]
@Versty same issue. Opened a known working website: On LTE (with AdGuard) the page did not load at all, resulting. in a safari error "server stopped responding", while the same site loads within a second or so on my wifi (with pi-hole). I used LTE for testing because AdGuard is disabled for my SSID.

**Comment by Versty** [comment]
@xdemiansmithx The Issue may be caused by your ISP blocking certain DNS. 
Keep using LTE for testing, add `8.8.8.8` as a custom DNS server, keep Safari protection disabled.
What is the result?

**Comment by xdemiansmithx** [comment]
You can't change the DNS for LTE in iOS though. I think DNS also would not interfere with accessing a local device with the IP address directly?

**Comment by Versty** [comment]
@xdemiansmithx Yes, DNS will not be involved if you're accessing a server with a specific IP directly. 
I suggested you to change the DNS server in the AdGuard app (Protection tab -> DNS protection -> DNS server), where you can choose one from the list or add a custom DNS. It would work, even if you are using LTE. 
For AdGuard DNS servers, you can check if the selected DNS is operating on your device on our test page [adguard.com/test.html](adguard.com/test.html). Also you can see processed requests in the Activity tab.

**Comment by Versty** [comment]
@xdemiansmithx 
Could you collect and send logs from your device? 
The logs would help us to investigate this issue. 

1. Open Settings --> General --> Turn **Advanced mode** on --> Advanced settings --> Turn **Debug logs** switch on;
2. Reproduce the issue and remember the exact time when it happened;
3. Disable "DNS Privacy";
4. Open the settings --> Support --> **Export logs**;
5. System popup will be opened --> Choose "Mail" app
6. Enter `apple@adguard.com` as a recipient;
7. Mention this issue number in the subject and add the time the issue was reproduced at.

**Comment by xdemiansmithx** [comment]
@Versty Hi Diana, sorry for the delay, I've been quite busy lately and thus had to completely disable asguard.

I've done a bit of further testing and the issue also happens when setting 8.8.8.8 as DNS in adguard, while safari protection was off. I have just now send the export as per your request.

Thanks a lot for looking into this!

**Comment by Versty** [comment]
@xdemiansmithx Thank you, logs have been received. We are examining it.

**Comment by xdemiansmithx** [comment]
Hi @Versty - any update on this? (And thanks for looking into this for me)

**Comment by Versty** [comment]
@xdemiansmithx Hi! 
Seems like your logs is not debug, so we don't have enough info to find the exact reason. 
Could you please collect new logs by following this guide step by step? 

1. Open **Settings** --> **Genera**l --> Turn **Advanced mode** on --> **Advanced settings** --> Turn **Debug logs** switch on;
2. Reproduce the issue and remember the exact time when it happened;
3. Disable "DNS Protection";
4. Open the settings --> Support --> Export logs;
5. System popup will be opened --> Choose "Mail" app
6. Enter `apple@adguard.com` as a recipient;
7. Mention `#2083` issue number in the subject and add the time the issue was reproduced at.

**Comment by Versty** [comment]
@xdemiansmithx Is this issue still relevant to you?
