### ISSUE TITLE
Since iOS 16, public wifi networks with captive portal no longer work (no connection possible)

### ISSUE THREAD

**Issue by nitram9** [AdguardTeam/AdguardForiOS#2110]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [YES] I am running the latest version
- [YES] I checked the documentation and found no answer
- [YES] I checked to make sure that this issue has not already been filed

### Issue Details

iOS >=16.0 

### Expected Behavior

Sign-in to public wifi networks with captive portal works with Safari iOS browser

### Actual Behavior

Sign-in to wifi networks with captive portal does not work with Safari iOS browser. Thi was tested on numerous different networks. Instead, Safari reports 'no network connection'. 

### Current Workaround

The solution for captive portal to work is to uninstall AdGuard and restart the phone.

**Comment by Versty** [comment]
@nitram9 Hi! We tried to reproduce this issue, but with no luck. 
Could you collect and send the logs from you device to help us investigate this case? 

Please follow the steps above: 
1. Open Settings -> General -> Turn **Advanced mode** on -> Advanced settings -> Enable **Debug logs**;
2. Reproduce the issue and remember the exact time when it happened;
3. Disable "DNS Protection";
4. Open the settings -> Support -> **Export logs**;
5. System popup will be opened -> Choose "Mail" app
6. Enter `apple@adguard.com` as a recipient;
7. Mention this issue number in the subject and add the time the issue was reproduced at.

**Comment by nitram9** [comment]
Hi Diana,Thanks for reaching out. Upon reinstalling the app today (following update to iOS 16.3), I can confirm that the captive portal redirect is working again. Either it was the fault of 16.2 or reinstalling the app did the trick. You can now close the ticket as the solution might just be to reinstall. Thanks On 26 Jan 2023, at 14:14, Diana ***@***.***> wrote:﻿
@nitram9 Hi! We tried to reproduce this issue, but with no luck.
Could you collect and send the logs from you device to help us investigate this case?
Please follow the steps above:

Open Settings -> General -> Turn Advanced mode on -> Advanced settings -> Enable Debug logs;
Reproduce the issue and remember the exact time when it happened;
Disable "DNS Protection";
Open the settings -> Support -> Export logs;
System popup will be opened -> Choose "Mail" app
Enter ***@***.*** as a recipient;
Mention this issue number in the subject and add the time the issue was reproduced at.
