### ISSUE TITLE
AdGuard for iOS disappears from iOS DNS selection with iOS Settings

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdguardForiOS#2203]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  -  4.5.0(1002)
- **Device model and storage size:**
  -  iPhone 13 Pro
- **Operating system and version:**
  -  iOS 16.6
- **Browser or App:**
  - 

### Expected Behavior

 When using native dns implementation within AdGuard for iOS,I expect to be able to select AdGuard within iOS Settings > General > VPN & Device Management when required.

### Actual Behavior

 When using native dns implementation within AdGuard for iOS, under certain conditions AdGuard will disappear entirely from iOS Settings > General > VPN & Device Management.
It will not able to be recovered until AdGuard is reset, or reinstalled.

### Screenshots

<details><summary>Screenshot:</summary>

https://github.com/AdguardTeam/AdguardForiOS/assets/95468948/8178daca-f25c-45f4-ae7a-333a45d318b2

</details>

**Comment by ESurina** [comment]
Please tell me more about the conditions under which this happens.

Also to troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:

1. Open Settings --> General --> Turn **Advanced mode** on --> Advanced settings --> Turn **Debug logs** switch on;
2. Reproduce the issue and remember the exact time when it happened;
3. Disable "DNS Protection";
4. Open the settings --> Support --> **Export logs**;
5. System popup will be opened --> Choose "Mail" app
6. Enter `apple@adguard.com` as a recipient;
7. Mention this issue number in the subject and add the time the issue was reproduced at.

**Comment by ESurina** [comment]
Seems that problem is that you use h3://26f49364.d.adguard-dns.com/dns-quer server. For native DNS mode you can only use DoT, DoH (http/2) or plain server. Please, try to choose any of these servers.

**Comment by ESurina** [comment]
We are planning to add a note for users in future versions.
