### ISSUE TITLE
AdGuard Pro DNS Protection: Mail content forever "loading"

### ISSUE THREAD

**Issue by sh2sg** [AdguardTeam/AdguardForiOS#2213]
- iPhone 14 Pro and iPad (8th generation)
- iOS 16.6
- Latest AdGuard Pro from AppStore
- Native Mail app
- iCloud Mail with custom domain
- Mail privacy is off

After enabled DNS Protection, I am unable to load mail content, the "Loading" spinning wheel stayed forever.

Turning off DNS protection solved the problem.

**Comment by ESurina** [comment]
To troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:

1. Open Settings --> General --> Turn **Advanced mode** on --> Advanced settings --> Turn **Debug logs** switch on;
2. Reproduce the issue and remember the exact time when it happened;
3. Disable "DNS Protection";
4. Open the settings --> Support --> **Export logs**;
5. System popup will be opened --> Choose "Mail" app
6. Enter `apple@adguard.com` as a recipient;
7. Mention this issue number in the subject and add the time the issue was reproduced at.

**Comment by ESurina** [comment]
Please, try using any AdGuard server (for example, Non-filtering with Regular protocol).

**Comment by ESurina** [comment]
Could you please disable AdGuard DNS filter and see if the problem is solved?

**Comment by ESurina** [comment]
Yes, most likely this was the reason. If you experience this problem again, please open the issue again.
