### ISSUE TITLE
YouTube video opens to black screen

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForiOS#2288]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 4.5.2
- **Device model and storage size:**
  -  iPhone 13 Pro 128gb
- **Operating system and version:**
  - iOS 17.3
- **Browser or App:**
  - Safari

### Expected Behavior

YouTube video loads

### Actual Behavior

YouTube video shows a black screen

### Screenshots

<details><summary>Screenshot:</summary>

https://github.com/AdguardTeam/AdguardForiOS/assets/149243371/37bedc93-bb88-46ec-a32d-788232b203cd

</details>

**Comment by maxikuzmin** [comment]
@kyjhoz-mikfip-goXci0 could you please clarify if you turn off AdGuard protection - does the problem recur?
Do you have third-party filters in AdGuard?

To troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:

- Open Settings --> General --> Turn Advanced mode on --> Advanced settings --> Turn Debug logs switch on;
- Reproduce the issue and remember the exact time when it happened;
- Disable "DNS Privacy";
- Open the settings --> Support --> Export logs;
- System popup will be opened --> Choose "Mail" app
- Enter apple@adguard.com as a recipient;
- Mention this issue number in the subject and add the time the issue was reproduced at

**Comment by maxikuzmin** [comment]
@kyjhoz-mikfip-goXci0 any news?
