### ISSUE TITLE
Allow signing in into the pay-once version

### ISSUE THREAD

**Issue by SpotlightForBugs** [AdguardTeam/AdguardForiOS#2316]
### Issue Details

I‘d love to be able to sign in into my AdGuard Account from the AdGuard Pro (pay once) app. 

### Proposed solution

Just add a (not forced but optional) login method. This could enable rule syncing etc. in the future.

**Comment by maxikuzmin** [comment]
@SpotlightForBugs would you like to sign in with an AdGuard Pro account where?

**Comment by SpotlightForBugs** [comment]
Into the app https://apps.apple.com/de/app/adguard-pro-adblock/id1126386264?l=en-GB

To enable settings sync across devices eg. all phones have those settings; all PCs those and so forth. I’d like my phone to appear on the adguardPro dashboard (in the web) without spending a key when you already have bought the full-fledged app. 

I am sorry for my English skills, please let me know if you need any more explanation

**Comment by maxikuzmin** [comment]
@SpotlightForBugs yes, I know what you mean :) 
We have a settings export/import feature to migrate settings from one device to another in Android, but this feature has not been added to IOS yet due to [backup size](https://github.com/AdguardTeam/AdguardForiOS/issues/551) issues
Duplicate of #1143
Please refer to issue 1143
