### ISSUE TITLE
Which, if any, Adguard userscripts are recommended for use with Adguard for iOS?

### ISSUE THREAD

**Issue by BillyJoeJimBob** [AdguardTeam/AdguardForiOS#2342]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

Using Adguard for iOS with Advanced protection enabled, is there currently any improved content-blocking benefit from also using any of the userscripts in https://adguard.com/kb/general/userscripts/ (AG Popup Blocker, AG Extra, AG Assistant, Disable AMP)?  That page is silent regarding using userscripts with AG for iOS, so it is not clear to me whether they are compatible, complementary or redundant to features already covered by iOS or AG. 

If any of these userscripts are recommended for use with AG for iOS, is there a recommended userscript manager? https://apps.apple.com/us/app/macaque/id1595306197?platform=iphone appears to be compatible with specific APIs used by AG Popup Blocker, I haven't seen anything mentioned about the other userscripts.

Thank you kindly for your insights on this matter.  I wasn't sure if I should ask this question here or at one of the AG userscript repositories (https://github.com/AdguardTeam/PopupBlocker etc.).  See: https://github.com/AdguardTeam/AdguardForiOS/issues/1542 &
https://github.com/AdguardTeam/PopupBlocker/issues/271

**Comment by tengizmax** [comment]
@BillyJoeJimBob ,such an interesting question you asked ! We've looked into it thoroughly, and here's what we've found:

We can't recommend any custom or open source  userscripts because the AdGuard for iOS app doesn't currently support adding them. We working on add this feature but still have some issues to resolve e.g. checking with App Store policies, installing arbitrary userscripts may be against it.

You're welcome to use any userscript manager you like, but it won't have any interaction with AdGuard for iOS.

You also asked if there would be any benefits to using userscripts alongside Advanced protection.  It's important to note that these are distinct concepts, and it's impossible to give a definitive answer. Advanced protection focuses on content filtering, while userscripts are specific, "targeted" sets of rules.

Anyway, stay tuned for future updates and thanks for your  cooperation.
