### ISSUE TITLE
Internet stops working intermittently with AdGuard DNS implementation 

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForiOS#2354]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.5.5

### Environment

- OS: iOS 17.5.1
- Device: iPhone 13 Pro

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard Tracking Protection filter

### Social

AdGuard Social Media filter

### Annoyances

AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter

### Security

NoCoin Filter List

### Advanced protection for Safari

- [X] yes, I do

### Which DNS server do you use?

AdGuard DNS

### DNS protocol

DNS-over-HTTPS

### Custom DNS

AdGuard Personal DNS

### DNS filtering

- [X] yes, I do

### Custom DNS filter

AdGuard DNS filter and AdGuard popup filter

### DNS implementation

AdGuard

### Tunnel mode

Split-Tunnel

### Low-level settings

Bootstrap server: default
Fallback server: default
Blocking mode, etc: default

### Issue Details

Steps to reproduce:
1. Browse Safari

### Expected Behavior

Safari works

### Actual Behavior

Safari intermittently stops navigating to pages until DNS protection is changed to either native implementation, or a mobile config, or turned off/on.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by maxikuzmin** [comment]
@emeritaacuity0u could you clarify more detailed steps to reproduce the problem? How long is the internet down when this problem occurs? 

Also we need to get the app logs.

Here's what we need you to do:

- Open Settings --> General --> Turn Advanced mode on --> Advanced settings --> Turn Debug logs switch on;
- Reproduce the issue and remember the exact time when it happened;
- Disable "DNS Privacy";
- Open the settings --> Support --> Export logs;
- System popup will be opened --> Choose "Mail" app
- Enter apple@adguard.com as a recipient;
- Mention this issue number in the subject and add the time the issue was reproduced at.

**Comment by ghost** [comment]
Given how intermittent it is, it's impossible for me to reproduce. I can confirm this issue isn't related to the network switching between mobile/wifi at the very least.

I'll reply back when it happens again.
