### ISSUE TITLE
ad is shown when you open YouTube and play the first vid

### ISSUE THREAD

**Issue by Rintaro-Sakamoto** [AdguardTeam/AdguardForiOS#2389]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.5.6

### Environment

- OS:17.6.1
- Device: iPhone12mini

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard Tracking Protection filter

### Language-specific

AdGuard Japanese filter

### Advanced protection for Safari

- [ ] yes, I do

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

DNS protection disabled

### DNS filtering

- [ ] yes, I do

### DNS implementation

DNS protection disabled

### Tunnel mode

DNS protection disabled

### Low-level settings

Bootstrap server:
Fallback server:
Blocking mode, etc:

### Issue Details

Steps to reproduce:
1. Open YouTube from Safari
2. Play any video on YouTube
3. Then ad is going to be shown as though adguard is working

### Actual Behavior

ad was shown

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by ESurina** [comment]
In order to troubleshoot this issue, we need to get your application logs.

Here's what we need you to do:

1. Open Settings -> General -> Turn **Advanced mode** on -> Advanced settings -> Turn **Debug logs** switch on.
2. Reproduce the problem, then remember the exact time it happened.
3. Open *Settings -> Support -> Export logs*.
4. System popup will be opened -> Choose **Mail** app.
5. Enter `qa@adguard.com` as a recipient and:
    - include `[iOS]` keyword and `ISSUE_NUMBER` in the subject of your email
    - specify the exact time when the issue occurred

**Comment by ESurina** [comment]
We found out that the problem is that you have advanced protection turned off. In order for advertising to be blocked on YouTube, it must be turned on.
