### ISSUE TITLE
Implement "Edit" mode in the filters list

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#30]
From #11 

> One more thing: Turning it on and off quickly wouldn't work that way nevertheless, since the app (or the OS) needs too much time to load the changed set of filters. It would not be possible to work through the filters list as fast as you read the filter names and swipe them to toggle just how you need them.

> So - with that in mind, it might be nice to have an edit mode. Like: have an "edit"-Button in the upper right (making that feature obvious), tap it, have all the > signs replaced with a toggle, work fast through the filter list toggling them as needed, tap "done", and wait until the new filter set is loaded.

> That way, you can first concentrate on customizing the filter list without constantly being interrupted by the app loading filters, and give the app time to load the filters when you are done.

**Comment by Stillness-2** [comment]
![01](https://cloud.githubusercontent.com/assets/12689/11100399/145fc3aa-88c2-11e5-91ab-28d6b9af001f.png)
![02](https://cloud.githubusercontent.com/assets/12689/11100402/1794cad4-88c2-11e5-8671-b32072c7b86e.png)

**Comment by ameshkov** [comment]
@dartrax what do you think?

**Comment by dartrax** [comment]
Hey that looks like being exactly what I meant! Awesome!

I'm not sure about the round buttons. I find it a little bit irritating that they look more like radio buttons (pick one option and the other ones get unpicked) than like check boxes (usually rectangle shape or on/off toggle). But, since there is more than one filter selected right out of the box, it should be clear enough that they do not behave like radio buttons. What was the reason for using round buttons?

It's really fun and interesting to participate! I'm looking forward to the next release :)

**Comment by ameshkov** [comment]
@Stillness-2 have we missed "check" icons?

!(http://www.oracle.com/webfolder/ux/mobile/component/img/checkbox-ios7.png)

**Comment by ameshkov** [comment]
@dartrax the latest beta is here with Edit mode and pretty checkboxes :)

**Comment by dartrax** [comment]
Yeah! Perfect!
I've not much time this week left since I move to a new home, but I'll take it for a test as soon as I can!

**Comment by dartrax** [comment]
Works like a charm =) *thumpsup*

**Comment by ameshkov** [comment]
:)
