### ISSUE TITLE
[Feature request] Adguard for iOS (Pro) widget

### ISSUE THREAD

**Issue by Darina655** [AdguardTeam/AdguardForiOS#312]
There is a question regarding Adguard Pro. If there are plans on
adding a widget in future updates? It would be a convenient way to toggle
the Express VPN connection and Adguard since they cannot be on at the same
time.

**Comment by ameshkov** [comment]
@Stillness-2 thoughts?

**Comment by Stillness-2** [comment]
I think we can do it

**Comment by seacatos** [comment]
+1

**Comment by altokarev** [comment]
One more +1 from Facebook:
>hello adguard team .. can you add widgets for  "adguard" ? that will be cool

**Comment by ypetruk** [comment]
Ticket ID: 1591354
Like adding a widget for the "Pro feature" of AdGuard: A quick toggle to turn on or off. 
-Some apps don't work without ads and you need to go to the application and turn it off. 
-Instead of that, could wire in a widget with the ability to turn off/on the "Pro feature" quickly. 

 <details><summary>Screenshot:</summary>

![image1](https://user-images.githubusercontent.com/28784344/28329494-ac174c3a-6bf2-11e7-8e6c-cb6a791d4200.JPG)

</details>

**Comment by IvanIin** [comment]
Unfortunately we can not make a switch like in adblock. IOs does not allow us to change the tunnel configuration from the today extension(https://forums.developer.apple.com/thread/42332). We can read the configuration profile, start and stop vpn. But our tunnel use the ondemand setting (which is set via the configuration profile) and automatically restarts.

**Comment by dayan50** [comment]
on issue
