### ISSUE TITLE
FRITZ!App Fon compatibility

### ISSUE THREAD

**Issue by oprotsyk** [AdguardTeam/AdguardForiOS#322]
FRITZ!App Fon https://itunes.apple.com/de/app/fritz!app-fon/id372184475?l=en&mt=8

Problem: A telephone app FRITZ!App Fon (fixed line connection over WLAN)  can not be used as it can not connect with VPN, without VPN everything works.

DNS logs in ticket 1472628

**Comment by i0s1q** [comment]
I Fix this Problem 

Open FRITZ!App Fon 
Tap More and Setting 
Tap Adresse delete fritz.box and add 192.168.178.1
Done

**Comment by Bohdan-SUP** [comment]
@Stillness-2 can you please check? seems like it helped on our end as well

**Comment by vozersky** [comment]
You need to have a FRITZ!Box to check it, I guess.

**Comment by ameshkov** [comment]
Just in case, `fritz.box` points to the localhost:
```
nslookup fritz.box 176.103.130.130
Server:		176.103.130.130
Address:	176.103.130.130#53

Non-authoritative answer:
Name:	fritz.box
Address: 127.0.53.53
```

I wonder, could it be the cause?

**Comment by maciboy** [comment]
This is a general issue if devices are configured to use a DNS other than the FritzBox itself. 
E.g. if you just configure the (iOS) device to use 8.8.8.8 (Google) as DNS, the issue is the same and Fritz!Fon App will be unable to connect to the FritzBox. 
This issue with name resolution can, as already described above, easily be solved by changing the address of the FritzBox within the Fritz!Fon app, so that resolution is not needed. 
In most cases: http://192.168.178.1

Related (german): https://www.heise.de/newsticker/meldung/Neue-Top-Level-Domain-box-bringt-manche-Netze-durcheinander-3491185.html

**Comment by ameshkov** [comment]
@maciboy thank you very much for the explanation!

I guess the issue will go away in the next iOS Pro major update (with #302).
