### ISSUE TITLE
[Pro] Add new localizations

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForiOS#325]
Following localizations are finished and are ready to be added:

- Chinese Simplified;
- Chinese Traditional.

**Comment by Stillness-2** [comment]
Added:
Chinese Traditional(zh-hant)
Portuguese (Brazil)(pt-BR)
Bulgarian(bg)
Estonian (Estonia)(et-EE)
Hungarian(hu)
Croatian(hr)

**Comment by lancelot-moon** [comment]
Hi, 
 
I am your Traditional Chinese translator of Adguard for iOS.
Originally, the Traditional Chinese translation was complete in old version of adguard pro.
But you released the new version which has new English strings.
I was busy before. So I didn't translate those new strings. 
Today, I saw that you released Adguard Pro v1.2.0 (incomplete Traditional Chinese translation) on Apple App Store. 
I went to complete the Traditional Chinese translation at once. 
May you use the complete Traditional Chinese translation in the next version of Adguard Pro? 
 
Thanks.

**Comment by vozersky** [comment]
reopened, 

@lancelot-moon  thank you so much for the cooperation!

**Comment by lancelot-moon** [comment]
@vbagirov
@Stillness-2
@ameshkov
@vozersky 

Hi,
There are something wrong when you took the Traditional Chinese translation from onesky.
I completed the translation.
But it's maybe because I didn't click "approve" button, those translations were not used when you took the Traditional Chinese translation from onesky.
http://i.imgur.com/ZAJHXoW.png

Some strings are still English and are not translated to Traditional Chinese in the interface of Adguard v1.2.1.
http://i.imgur.com/ULIYFZB.png
http://i.imgur.com/iHgKSy2.png

I already clicked "approve" button for those strings on onesky.
May you update the Traditional Chinese translation in Adguard?

Thanks.

**Comment by ameshkov** [comment]
@lancelot-moon yep, strings should be approved indeed. We'll do it for the next update.

**Comment by lancelot-moon** [comment]
@ameshkov

Hi,
Maybe there is the same problem in other language files.
Some translators don't know that we need to click "approve" button after completing translations.
Before taking translations from onesky, maybe your engineer needs to help to approve those strings.

B/R

**Comment by ameshkov** [comment]
@lancelot-moon the thing is that we should've approved it all on our own, but for some reason missed to do it. We'll be more careful next time.

**Comment by ameshkov** [comment]
Done
