### ISSUE TITLE
DNS server too far and too Google

### ISSUE THREAD

**Issue by Itsnothectic** [AdguardTeam/AdguardForiOS#336]
Google DNS for a privacy centric app is not a great choice. I think something such as d0wn resolver would be great, these are DNSSEC with No logs. Currently for some reason Adguard has me using two servers in Finland.
This DNS in Finland is owned by Google but has poor security, maybe because I am geographically far?

DNS spoofability test:
https://www.grc.com/dns/dns.htm

This is the website for d0wn https://dns.d0wn.biz/

**Comment by Itsnothectic** [comment]
It also performs poorly for spoofability

https://www.grc.com/dns/dns.htm

**Comment by ameshkov** [comment]
AG DNS is a recursive DNS, there are quite a few servers in the upstream.

I've explained it once here:
https://github.com/AdguardTeam/AdguardDNS/issues/110#issuecomment-272860066

**Comment by ameshkov** [comment]
Regarding DNS servers being too far, that's right indeed. We'll extend the number of DNS servers available, though.

Also, starting from the next Adguard version, there will be an option to block ads without using a third party dns server at all.

**Comment by Itsnothectic** [comment]
I could be wrong but isnt it best to only allow one DNS server for each user based on geolocation or user preference(I have ls.apple.com blocked). 
All the DNS servers used log. It would be nice if we could specify our own at least.

One strange thing is I live in Australia yet when my phone turns on and it contacts apple.com it uses foreign mirrors unless I block those for example apples-msk.ru

**Comment by ameshkov** [comment]
> One strange thing is I live in Australia yet when my phone turns on and it contacts apple.com it uses foreign mirrors unless I block those. I guess this can be good for decentralization but it seems to always be the same 2 foreign mirrors.

I suppose it uses the closest AG DNS server all the time and that explains everything.

Wanna try a beta version?

**Comment by Itsnothectic** [comment]
I would need a phone void of warranty to test because I feel I need to disconnect the battery to properly test issues.

I think the problem may only occur if lcdn-locator.apple.com is blocked.

However I did notice sometimes it has used yandex DNS and sometimes OpenDNS, I do not know enough about DNS to know if something is a bug or not but I see some servers listed from the GRC page could have better security.

The link to test is the GRC one in the first post.

**Comment by ameshkov** [comment]
> However I did notice sometimes it has used yandex DNS and sometimes OpenDNS, I do not know enough about DNS to know if something is a bug or not but I see some servers listed from the GRC page could have better security.

Unless GRC learns about Adguard DNS, it will show you random results all the time.

Here is what they do:
1. They generate a unique domain name (something like 123123123123.grc.com).
2. They initiate a web request to that domain name.
3. This request, in turn, initiates a DNS request.
4. **Important step**: they go through the list of the known DNS servers and check if this domain is cached in any of them.

Adguard is a recursive DNS, so your initial DNS request might be executed against a random DNS server we have in the upstream, that's why the test shows different result all the time. If they knew about Adguard DNS, they would use it on step 4 and show you the proper result.

Regarding privacy concerns, the DNS request is executed on Adguard's server behalf, upstream DNS does not receive any of your data.

**Comment by Itsnothectic** [comment]
Thanks. I understand now and I see the servers adguard uses are running DNS Crypt so security is very good also.

I will close because of a misleading title.
