### ISSUE TITLE
"No Configured Email"

### ISSUE THREAD

**Issue by nalvarez2007** [AdguardTeam/AdguardForiOS#379]
This might just be me being stupid, aka user error, but I cannot figure out where to configure my email to report incorrect blocking or missed ads. Every time I try, I get the following error:

<details>

![img_0672](https://cloud.githubusercontent.com/assets/4855771/25094942/28171ede-234e-11e7-9808-769d0ed05315.PNG)

</details>

**Comment by vozersky** [comment]
@nalvarez2007 

Hello! 
We use standard iOS "Mail" app for sending bug reports. In order to send one, you have to go to "Settings" -> "Mail" -> "Accounts" and add an email account. 

Please also note, there is a bug with reports that are sent from Safari action extension in Adguard 1.2.0: #378 
It has been already fixed in beta version.

**Comment by worldsdream** [comment]
When there is no email setup in mail>accounts. We should see a contactform. That way everyone can easily send reports.

**Comment by vozersky** [comment]
@worldsdream yeah, contact form would be  a proper way to do that, let's keep it as an improvement request: #387
