### ISSUE TITLE
High battery drain due to the Adguard VPN

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#391]
Дело в том что при включённом VPN мой расход заряда аккумулятора увеличивается в разы и при активном пользовании телефоном разряжается на 30-40 % за 2 часа, в то время как при выключенном VPN соединении и такой же активностью эти 30-40% израсходуются в течении 5 часов. Я не знаю может дело именно в том включен или выключен VPN , может быть он у всех так подъедает батарею, прошу Вас помочь мне в решении данной так сказать проблемы, уж очень понравилось ваше приложение и не хотелось бы удалять его из-за расхода батареи.

Кушает **только когда включен статус PRO**. А так всё работает.

ID: 1543786

**Comment by ameshkov** [comment]
Может там iOS9?

**Comment by evgeniy-ADG** [comment]
OS: 10.3.1 там.

**Comment by ameshkov** [comment]
@Stillness-2 есть что в логе полезное?

**Comment by X8716e** [comment]
I'm experiencing same issue iOS 10.3.2.

**Comment by c0ke2** [comment]
I like to app it is very good. But app is draining power when PRO is enable on  iOS 10.3.2

Please fix to this issue.

**Comment by vozersky** [comment]
@X8716e what about the latest beta build, does it bring any change? If you don't have a beta access yet but want to try it, let me know

**Comment by vozersky** [comment]
@X8716e @c0ke2  could you please send us your log files and let me know your customer IDs afterwards? ("send bug report" on the app's main screen)

**Comment by c0ke2** [comment]
Hello,

Many times I tried send log files. May be 4 or 5 times but unfortunately support team always said me no attachment at mail. But I see files whiling send log mail...

Btw I don't how to installing beta version of Adguard Pro on iPhone?


iPhone'umdan gönderildi

Vladimir Ozersky <notifications@github.com> şunları yazdı (10 Tem 2017 19:48):

**Comment by zebrum** [comment]
@c0ke2 support team meant that your letter was empty and they did not really know what your problem was. 
Please post here user ID - you will find it in autoreply letter from support team.

If you are ready to try Adguard beta, send me your apple ID via private messages on  [Adguard forum](https://forum.adguard.com/index.php?conversations/add&to=zebrum)  
or 'send bug report' in Adguard  app and I'll add you to beta test.

**Comment by c0ke2** [comment]
Hi,

  **User ID**: 1579837
 
And I sent you a private message.


iPhone'umdan gönderildi

Marie <notifications@github.com> şunları yazdı (11 Tem 2017 15:45):

**Comment by X8716e** [comment]
## @vozersky 

Apologies for my late response. I've actually been a beta tester for quite some time now (unable to remember precisely how long, though). I've another name on the Adguard forums, and use github for all reporting of discoveries, whether temporary workarounds for people experiencing issues or posting issues I may be experiencing.

Also, the the latest beta release as well as the one prior - when full tunnel mode was introduced function(ed) quite outstanding for me. I've not as much time as of late to take part in any GitHub projects with which I'm involved, though I will soon again, thankfully.

**Comment by vozersky** [comment]
@X8716e how's 1.3.3?

**Comment by X8716e** [comment]
@vozersky , funny you ask. I wanted to return to this topic to state that **_battery usage is significantly_** **_higher when not using AdGuard Pro_**. So, in essence _the current release noticeably reduces battery drain_. This may of course be due to how I use my iPhone which may lead this phenomena. Others may see varying results. However, I am certainly enjoying the _battery savings AdGuard Pro is giving me_.

**Comment by vozersky** [comment]
@X8716e good to hear, thanks mate. Well, I haven't noticed any battery issues as well. Closing then.
