### ISSUE TITLE
[Feature request] Inverted whitelist

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardForiOS#431]
User asked to implement to our iOS app the inverted whitelist that blocks nothing, еxcept that in the list. Just like in our extension.

![screen-shot-2017-07-05-at-20 34 22](https://user-images.githubusercontent.com/28726429/27877113-1bb20aa2-61c2-11e7-835d-c44e791135bd.png)
Got a feature request from the [Twitter](https://twitter.com/rjonesy/status/882287140394106880).

**Comment by ameshkov** [comment]
This is actually possible (at least we were able to do this in the Safari extension).

Let's wait for people votes, does anybody need it?

**Comment by Bohdan-SUP** [comment]
I'd like to see this if my vote counts :)

**Comment by X8716e** [comment]
If by inverted whitelist it's meant that it would block *all resources* except for (a) whitelist rule(s), then I vote yes. Although if I'm misunderstanding this due to my lack of seeing this (missing it?) in the FF extension on Linux, my interpretation would be accomplished simply by using the wildcard * to block all but what is given express permission by the user. Either way, yes.

**Comment by ameshkov** [comment]
> Although if I'm misunderstanding this due to my lack of seeing this (missing it?) in the FF extension on Linux

It should be there, right in the "Whitelist" settings section
