### ISSUE TITLE
Adguard pro 1.2.2 beta(95) does not work in ipv6 only networks

### ISSUE THREAD

**Issue by IvanIin** [AdguardTeam/AdguardForiOS#436]
> In the latest Ad Guard Pro beta version(1.2.2 95), it is still unstable. Under full tunnel, it will automatically restart when I switched Wifi to cellular service. Besides, it takes several minutes to load the website page when I used cellular service. 

customer 1408227

**Comment by ameshkov** [comment]
@altokarev please inform the user that there's not much we can do due to his ISP limitations.

Here's what's going on:

1. His cellular network is IPv6-only.
2. AdGuard does not provide IPv6 DNS servers, so when he tries to use our regular IPv4 DNS, all the requests fail.

The only option at the moment is to stick to the system-wide ad blocking and not change DNS settings:(.

**Comment by altokarev** [comment]
Done.

**Comment by ameshkov** [comment]
Let's at least detect that situation and warn the user that remote DNS won't work as he is in the IPv6-only network.
