### ISSUE TITLE
AdGuard Pro for iOS Recommendation

### ISSUE THREAD

**Issue by UmarFarq** [AdguardTeam/AdguardForiOS#487]
Since Apple are Tightening their rules on the app store and AdGuard has to adapt to the changes, I have come across another method that will totally bypass the need to install AdGuard via app store.

AdGuard is a brand that has been around for long time and very trustworthy, I wouldn't trust a new Company and not promoting them in any way. I am only sharing the link so AdGuard can take a look at their approach and maybe develop AdGaurd Pro for iOS with this method.

Please take a look at https://adblockprime.co and the way they implement ad blocking via a profile install.
Also AdGuard can also update filter lists in the background via the profile and would be a one click solution for everyone 

Maybe AdGuard can have a similar approach? 

What do you guys think?

**Comment by UmarFarq** [comment]
AdGuard can also update filter lists in the background via the profile and would be a one click solution for everyone

**Comment by zznosar** [comment]
As a user of Adguard PRO, i want an app that I can use to toggle off and on the app. Also the ability to blacklist and whitelist websites. The ability to use the blocking in Safari only without affecting other apps in the system. I'm very much happy with the current set up since I can customise it the way I want it and base on my needs. The above idea is fine, but i don't think not all users will appreciate this as this is taking away the ability to customise stuffs. Just my two cents...

**Comment by ameshkov** [comment]
> Maybe AdGuard can have a similar approach?
> What do you guys think?

Actually, the current version allows you to have system-wide ad blocking. Just copy/paste [the simplified domain names filter](https://adguardteam.github.io/AdguardDNS/Filters/filter.txt) contents into the blacklist and that's it. The problem is that there's no auto-update, you'll have to do it manually. The same goes for the adblockprime, though.

What's better in AG is that you can change the settings any time, add any domain to blacklist/whitelist. That's technically not possible with an MDM profile.

**Comment by ameshkov** [comment]
Oh my, read these guys privacy policy and terms before giving it a try:
https://adblockprime.co/privacy.html

And take a look at the permissions they acquire:
![photo_2017-08-28_20-34-37](https://user-images.githubusercontent.com/5947035/29785460-59ad1bb0-8c30-11e7-9920-3e826dd6247c.jpg)
