### ISSUE TITLE
AdGuard or Adguard on oneskyapp's translations of Adguard for iOS

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#509]
@aalpatkina

Hi,

Ever you changed Adguard to AdGuard on oneskyapp's translations of Adguard for iOS.
I completed the changes.
But you recovered those AdGuard to Adguard afterwards.
What's the situation?

Thanks.

**Comment by aalpatkina** [comment]
@lancelot-moon 

Hi,

We will use this way of writing  - AdGuard.
It was impossible to change Adguard to AdGuard in 'Adguard for iOS - iTunes App Store (PRO)' project earlier because of the charecter limit. But we updated the original phrase and changed the word.

As about 'Adguard for iOS - iTunes App Store' it is still impossible there to change the product name in the original phrase because of the phrase's length. But currently we won't change anything there. So, you can translate or approve the translations with 'AdGuard'.
