### ISSUE TITLE
Add Quad9 to the list of known DNS Servers

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#529]
https://www.globalcyberalliance.org/initiatives/quad9.html

**Comment by lancelot-moon** [comment]
@ameshkov
@vbagirov

Hi,
Please read the #69 article.
https://malwaretips.com/threads/which-dns-server-do-you-use-dns-tunnelling.62939/page-4

May you also add these DNS servers in the list of known DNS providers?
FoolDNS:
87.118.111.215
213.187.11.62

GreenTeam Internet:
81.218.119.11
209.88.198.133

Fortinet Secure DNS:
Fortinet Secure DNS (malware/phishing/malvertising/botnet blocking)
208.91.112.53
208.91.112.52
208.91.112.220
80.85.69.54

Alternate DNS:
198.101.242.72
23.253.163.53

Neustar DNS Advantage:
156.154.70.2
156.154.71.2

You only give 1 custom DNS server in AdGuard for Android and 10 custom DNS servers in AdGuard Pro for iOS.
May you give more custom DNS servers (15 or 20) for AdGuard (both Android and iOS version)?
We can add not only global DNS servers but also some local ISP's DNS servers by ourselves.

Please change the layout of DNS servers to drop-down menu.
It's better that the DNS servers' ip are directly shown on screen since we choose a DNS server.

Thanks.

**Comment by ameshkov** [comment]
> May you also add these DNS servers in the list of known DNS providers?

Moved to a new issue:
https://github.com/AdguardTeam/AdguardForiOS/issues/543
