### ISSUE TITLE
Reduce the size of backup for iCloud Backup

### ISSUE THREAD

**Issue by atkrv** [AdguardTeam/AdguardForiOS#551]
A user asked to reduce the size of AdGuard's backup for iCloud Backup.

>The question I had was why is your backup so large? It’s more than 20MB in my iCloud backup and it seems like overkill. Can you just ignore some files and keep the settings only?

We should separate settings from app's files I think.

**Comment by BrokenHope** [comment]
Did this never get looked into? my iCloud Backup is over 80MB, seems large for this type of app.

**Comment by ameshkov** [comment]
Not yet, too busy trying to resolve some mysterious network-level bugs which are the highest priority at the moment.

**Comment by Ryan-Goldstein** [comment]
I just came here to report this in the latest beta (3.0.0 (140)).

I installed AdGuard just a bit over a week ago, and in Settings > Apple ID > iCloud > Manage Storage > Backups > This iPhone, it shows AdGuard taking up 139.2 MB, which is by far the largest app there except for my Photo Library.

I'd guess that most of this is attributable to the DNS Requests Log, since it appears to grow indefinitely with no way to clear it. If so, in addition to the unnecessary iCloud data storage, this is a pretty serious privacy issue.

One of the primary reasons that people use DOH/DOT is to prevent their ISP and other intermediaries from seeing their DNS requests. It looks like in the default configuration, the full list of all DNS requests made through AdGuard are backed up to iCloud, contradicting the name of the Settings section itself ("DNS privacy").

Thanks for your consideration, and for all of your work on this excellent app!

**Comment by Versty** [comment]
@atkrv We have recently discussed this improvement, optimizing the size of iCloud Backup is not planned for upcoming versions. Therefore, this issue is closed until a more opportune time.

**Comment by dotext** [comment]
Hi @ameshkov and/or @maxikuzmin, what would be the status for consideration these days?

I’ve just noticed that my AdGuard data for iCloud Backup is increasing more and more, and it’s currently using 223.5 MB of my iCloud Data. I’m not sure why it is storing that much.

<img width="400" alt="Image" src="https://github.com/user-attachments/assets/724bb4e6-0c30-4251-8ede-df53008d14e9" />

**Comment by maxikuzmin** [comment]
@dotext sorry for the delay, I'll reply to your issue

**Comment by dotext** [comment]
Not a problem @maxikuzmin, thank you.
