### ISSUE TITLE
A possible educational enhancement for the project’s README.md file.

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForiOS#565]
Section 2 within the disclaimer states :
> - AdGuard Pro for iOS is also an open source product despite being a paid app. Its code can be found in this repository.

This is, essentially, the definition of Free Software famously used by the Free Software Foundation as crafted by Richard Stallman himself - www.fsf.org/about/what-is-free-software. My proposal is to simply point the AdGuard Pro for iOS community to that page. I believe doing so would lead to a more enlightened community in respect to “Free” software (or Open Source, as today the two definitions are often used to mean the same thing). Thank-you all!

“Free software is a matter of liberty, not price. Think of “free” as in “free speech”, not as in “free beer”. Free software is a matter of the users' freedom to run, copy, distribute, study, change and improve the software.” - an excerpt of the Free Software Philosophy.

**Comment by X8716e** [comment]
Related, though not directly to README.md : the Free Software Foundation has both corporate patrons, which is a relatively small list due to donation requirement, as well as a directory of over 16k projects that comply with the meaning of Free Software. Check out the 2nd project in the Security/Internet section: https://directory.fsf.org/wiki/Category/Security/internet. Personally, I think it would be quite excellent to see AdGuard here, regardless of which specific project(s) are accepted by the Foundation. Both AdGuard Pro for iOS & its Android counterpart would meet the requirements with possible adjustments to wording used regarding specifics that the FSF may ask for. And this despite both programs being run on proprietary devices (Android too is a proprietary OS - it has devolved into one over time).

**Comment by ameshkov** [comment]
> “Free software is a matter of liberty, not price. Think of “free” as in “free speech”, not as in “free beer”.

Makes sense indeed :)

However, the two points there are linked.

> AdGuard for iOS is a free app. We believe that all free products should be open source, and AdGuard for iOS is not an exception. Its code can be found in this repository.

This is actually our policy on open source. It is based on the idea that a free app that has access to any sensitive personal data must be transparent to its users. This helps the app to avoid the temptation of dubious monetization methods (usually related to selling data).

It's important to note, though, that our paid products are generally not open source. The tech used by all the AG versions is our know-how and we're too afraid of clones.

> AdGuard Pro for iOS is also an open source product despite being a paid app. Its code can be found in this repository.

And here goes our experiment. AG Pro is the first paid product we decided to make fully open source despite it being paid.

The result is controversial so far. On one hand, collaboration and the help from the community are awesome, and it helps a lot. On the other hand, the clones menace appeared to be very real:) There're quite a few AG rip-offs on the AppStore, not to say that shortly after the AG Pro release, the very same functionality was introduced by a couple of competing apps (closed source btw).

My take on this is:

* GPL does not protect you from rip-offs, and it's simply too expensive to go after them.
* Choose wisely what to open source. I like how it's explained here: http://tom.preston-werner.com/2011/11/22/open-source-everything.html

**Comment by X8716e** [comment]
@ameshkov , I was just reading today regarding your proprietary products. However they by no means will exclude having AdGuard Pro listed in what is essentially the brainchild of Richard Stallman, a ’god’ of sorts in the FOSS community. Just check out any of his numerous talks & see his equivalent of Beetles fans circa their early years. Just in Stallman's case the audience is filled with the nerdiest of nerds - watch the reaction of the women - instead of pop music teeny boppers.

GPLv(n) is not the Liscence to use,, though courts have upheld it when open source work using said licence has been incorporated into proprietary works without the precise requirements stated in the GPL being fully upheld - including attaching that license, all proper credits, and making the code easily available for users to inspect for changes, sec flaws, etc.

**Comment by X8716e** [comment]
@ameshkov ::
—-
https://www.gnu.org/licenses/gpl-faq.html
—-
https://www.gnu.org/licenses/gpl-violation.html
—-
https://choosealicense.com/licenses/agpl-3.0

**Comment by X8716e** [comment]
> The result is controversial so far. On one hand, collaboration and the help from the community are awesome, and it helps a lot.

Without community contributions, motivations, etc, AdGuard Pro for iOS v2.00 would not have been the very first product of its kind - functioning DNSCRYPT on iOS ! plus filter subscriptions. Remember when DNSCRYPT was initially suggested in the forum? Well now it’s here. And for what it’s worth I’m proud to have been witness to its birth. Moreover, I would be one of many never to even know your product existed if it were not open source.

**Comment by ameshkov** [comment]
Regarding the readme, I agree that we can re-phrase it better, instead of "despite being a paid product" we can elaborate on our open source policy below and state that AG Pro for iOS is an exception that we made to see how it works out.

**Comment by aehlke** [comment]
If you take community contributions under GPL, those contribulations cannot be deployed to the App Store. You must require CLA or dual licensing external contributions to avoid violating GPL

**Comment by ameshkov** [comment]
Unfortunately, AG for iOS is one of the rare repos where people just do not contribute anyways. The libraries that it uses (like SafariConverterLibs or DnsLibs) where we do receive contributions sometimes are under a permissive license.

But it's a good point about CLA, thank you

**Comment by aehlke** [comment]
Looks like App Store policies have changed and may now be GPL compatible btw, due to being able to replace EULA for user.
