### ISSUE TITLE
Indicate what exact "blocking list" has blocked a request

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#584]
Currently, it just prints "Blocked by blacklist"

**Comment by lancelot-moon** [comment]
This issue is still not solved in beta v2.0.0(132).
If using default AdGuard SDN filter in subscriptions, the status in blocked DNS request will only show "blocked by blacklist".
It should indicate AdGuard SDN filter has blocked the request.
But it doesn't normally show "blocked by AdGuard SDN filter".
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/3cXAdrR.png)
</details><br/>

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/z3VUC3n.png)
</details><br/>

**Comment by ameshkov** [comment]
We'll resolve it in the next major update
