### ISSUE TITLE
NON-ISSUE

### ISSUE THREAD

**Issue by X8716e** [AdguardTeam/AdguardForiOS#593]
As everyone can see, and to my own amazement, I have ~70k filters currently in use. I added hpHost’s ATS on a whim, because of commenting on the fact that that list alone nearly maxes out the 50k limit. Well, all is well here in intr0land with it plus my original set loaded into AdGuard Pro for iOS. If it continues to behave, I’ll add another list to see what happens. And I’ll update everyone on the experience. This release seems to be a true workhorse. And I’m still using my iPhone 6 Plus. 💯 
![5fc07ee1-a9c9-463e-82c1-105a05bbf972](https://user-images.githubusercontent.com/18148748/34909571-d65ad514-f871-11e7-893b-5e346e46cc0d.png)

**Comment by zznosar** [comment]
@X8716e 
Ohh. You are using an older device! Cool. :-) Because i experience some weird issues in my ipod touch 6th gen which has the same specs of iphone 6! I have an issue number raised for that.

If your device is ok, then probably that issue is device specific.

Also there is a bug in the blocklist. Just dont go playing around with both dns setting and blocklist, else your subcription will be lost. I raised an issue with that as well. There is a video on how to reproduce!

**Comment by ameshkov** [comment]
> the 50k limit

This limit applies to Safari Content blocker only.

We don't limit the number of rules in the DNS blocking lists/hosts. However, if memory usage exceeds the iOS limit, it will cause some troubles (tunnel crashing, no internet, this kind of stuff:))

**Comment by X8716e** [comment]
Cool. Much appreciation for that knowledge.

**Comment by X8716e** [comment]
@zznosar   Yeah. I never upgrade devices until crapple forces the issue.
