### ISSUE TITLE
Add an option to hide DNS servers user doesn't want to use

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForiOS#623]

**Comment by lancelot-moon** [comment]
AdGuard DNS servers list is too long.
That's why I suggest to improve the layout of DNS setting and give my idea.
https://github.com/AdguardTeam/AdguardForiOS/issues/591

On the screen of DNS setting, only show the DNS information (DNS server's name, ip and description ) which a user chose.

About the selection of DNS server, all DNS servers are shown in another screen.
Users choose a DNS server there.
