### ISSUE TITLE
“Report an issue” menu item has been reowrked

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#649]
1. Please change "Report Missed Ad" to "Report Issues" in "Contact Support" of AdGuard Assistant.
Now, I only see "Web Reporting Tool" in "Contact Support" of AdGuard Assistant for reporting missed ads.
However, as what we know, "Web Reporting Tool" isn't only for reporting missed ads.
It can let us report several types of events: missed ads, anti-adblock and so on.
https://reports.adguard.com/en/new_issue.html

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/EcfpQmQ.png)
</details><br/>

2. May you also add "Web Reporting Tool" in the section of "More"?
"Web Reporting Tool" in AdGuard Assistant isn't obvious for users.
Please add "Web Reporting Tool" in the section of "More".

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/gU7YKeh.png)
</details><br/>

Thanks.

**Comment by lancelot-moon** [comment]
@ameshkov 
@IvanIin 

Sir, you use "Contact the Support" instead of "Report Missed Ad" in "Contact Support" of AdGuard Assistant. [ beta v2.0.0(136) ]
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/ACC4l9G.png)
</details><br/>

May you change "Contact the Support" to "Report Issues"?
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/nE9fB30.png)
</details><br/>

What do users contact Support for?
For what?
Chat with AdGuard Support?
Is there a pretty girl in AdGuard Support?
Please agree me to always contact AdGuard Support until she allows me her VK account and phone number.
PS. Please don't tell me about the fact in AdGuard Support if it can break my fancy.
[ Forgive for my poor humor if it's not amusing.
Take easy. Just for a knowing smile.)) ]

We need to define a simple explanation in the description of "Contact Support".
What's the difference if using "Contact the Support" in the description for "Contact Support"?
Please change "Contact the Support" to "Report Issues" in "Contact Support" of AdGuard Assistant..

Thanks.

**Comment by ameshkov** [comment]
> May you also add "Web Reporting Tool" in the section of "More"? "Web Reporting Tool" in AdGuard Assistant isn't obvious for users.

Here's what I suggest

1. Instead of "Send Bug Report" let's have a "Report an issue" button.
2. Tapping on it opens an [action sheet](https://developer.apple.com/ios/human-interface-guidelines/views/action-sheets/) with the following options:
    * Incorrect Blocking / Missed Ad
    * But Report
    * Contact Support
    * Cancel

* `Incorrect Blocking / Missed Ad` -- opens https://reports.adguard.com/new_issue.html with no params save for product type/version
* `But Report` -- opens `https://agrd.io/report_ios_bug` (link is to be created) that leads to a Wiki article here in this repo: https://github.com/AdguardTeam/AdguardForiOS/wiki/How-to-report-a-bug
* `Contact Support` -- opens mail app (the old way)
