### ISSUE TITLE
Please add "CANCEL" in the dialog of clearing the log. [ v2.0.0(132) ]

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#652]
**EDIT (by @ameshkov): https://github.com/AdguardTeam/AdguardForiOS/issues/652#issuecomment-366764929**

Maybe users regret clearing the log after clicking "Clear".
So please add "CANCEL" in the dialog of clearing the log.

Most people are right-handed.
I guess that "NO" button is frequently used.
So it's in the right.

"CANCEL" button is not frequently used.
So it's in the left.

You maybe anew define the size of dialog and color for cancel, yes and no.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/wQJ8h6M.png)
</details><br/>

Thanks.

**Comment by Sailor-Chibimoon** [comment]
Hello. I’m here just to ask a question since i saw this. I am mow excited with v2.0. Nothing much. 😊 what’s the difference between “NO” and “Cancel” in terms of functionality? Because i think No will function as Cancel as well right? Sorry about last time. Apologies. ✌🏻✌🏻✌🏻

**Comment by camelot-sun** [comment]
I'm sorry, I will be harsh in my comment. But this is the dumbest request I have ever read. Clearly this person does not know anything about iOS Programming and Apple Standards. If AdGuard Team do this, I doubt if apple will approve it. There should only be two selection in general. It is also stated in the Apple Developers Guidelines and Standards. If this will require three selection, then they need to redesign the whole button it self and use a different coding and approach.

In standards there should only be two buttons:

YES
NO

or

OK
CANCEL

There is no in between. 

Also, I simply don't understand why the requestor want to add a CANCEL button if there is already a NO. It's making the app and selection convoluted and will create confusion. I, my self, is 100% completely against this.

To the team, please do not do this request. I am an iOS developer too, but never in my life have coded three selections in a button. With two negative and one positive.

This will be totally out of the Apple Standards and apple way of doing things. Never can you find any system dialog (that is non-jailbroken) that has three button selection like the screenshot above.

I am an AdGuard user my self, but please don't do this.

Apologies if I am harsh, but as an iOS Developer,  I cannot contain my emotion if I saw this kind of weird request.

**Comment by lancelot-moon** [comment]
Regardless of clicking "YES" or "NO", the log will be cleared.
It's because that "YES" and "NO" are actually for resetting DNS requests statistics or not.

Maybe you're not a tester, so you don't touch beta v2.0.0(132).
You should know the meaning since you can see my screenshot unless you don't understand English.

So I wish to add a "CANCEL" botton for terminating clearing the log.

**Comment by camelot-sun** [comment]
If I can't understand english then why am I typing right now in english words? Your screen shot is obviously wrong. You should have request the below format instead which is acceptable in Apple Guidelines and Standards. Though I have to admit that your photoshop skills is good.

In your screenshot, even If someone from the dev community sees this, they will 100% object. I don't need to be a tester to know what is right or wrong. It is stated in the documentation. and I am 100% certain that if they do the screenshot that you want, apple will reject it due to inconsistency. 

This is the acceptable format in my opinion.


![uialertcontroller-action-sheet-automatic-style](https://user-images.githubusercontent.com/36351583/36071145-cc7c1b04-0f5d-11e8-93d3-11f6dff5c5af.png)

**Comment by lancelot-moon** [comment]
> Also, I simply don't understand why the requestor want to add a CANCEL button if there is already a NO. It's making the app and selection convoluted and will create confusion. I, my self, is 100% completely against this.

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/vLFUzL1.png)
</details><br/>

According to your words, you surely didn't know why to request a "CANCEL" button.
You didn't know that "YES" and "NO" are actually for resetting DNS requests statistics or not, and then the process is must along with clearing the log.

> In your screenshot, even If someone from the dev community sees this, they will 100% object. I don't need to be a tester to know what is right or wrong.

It's because you're not a tester, you didn't know why.
Simply, I just mentioned my thought to AdGuard team.
We need a "CANCEL" button for terminating clearing the log.
How to achieve it?
AdGuard team will think about it.

Well, you still mentioned a good idea for 3 selections (cancel, yes and no) as the reference.

**Comment by camelot-sun** [comment]
You don't need to screenshot what I said earlier, as the details are still true.

I am basing the requirement to the screenshot you want and with the guidelines apple has. At it's current form, your request of having three selection in a pop up system dialog box is not per standard and will only cause confusion since this dialog is not intended to have three actions.

We can only have YES and NO or OK or OK and Cancel. Cancel will function as NO if they do the way you want it. 

This is the way you want it:

![68747470733a2f2f692e696d6775722e636f6d2f77514a3868364d2e706e67](https://user-images.githubusercontent.com/36351583/36071508-59beade2-0f63-11e8-86ed-2faaac14d634.png)

**This is the way it should be, If you want apple to approve it, and it you want it to be consistent with iOS system dialogs.**

![uialertcontroller-action-sheet-automatic-style](https://user-images.githubusercontent.com/36351583/36071520-90912b88-0f63-11e8-8b50-e5a2cd44264c.png)

**Don't confuse the two. What you want is a Alert Pop Up Selection. The one that has three actions is a UI Sheet Action view.**

If you want to have to have CANCEL in the app, then request the UI Action Sheet instead of the Alert Pop Up.

Anyway, I am just helping you to understand the correct way of putting the cancel and dialog boxes in your request so that apple will not reject it. Because you cannot just simply photoshop it and ask the team to do it. that is the reason why at first glance, having cancel and no does not make any sense. Just my opinion.

And also, please don't confuse **testing** and **requesting**. Me as an iOS Developer, I am required to do my own test as well called "UNIT TEST" so I know. I may not be an AdGuard Beta Tester for now, But I will apply in the future once I move across all my projects in GITHUB.

**Comment by lancelot-moon** [comment]
I didn't misunderstand.
You mentioned **TWO** points for my request.
One is the format of 3 selections in a dialog.
Another is what you didn't know why I request a "CANCEL" button.

You say that you're an iOS developer.
Well, you gave a good idea for 3 selections in a dialog.
That's all.

Is camelot-sun your main account?
I don't think you're a freshman on GitHub since you say that you're an iOS developer 
sun... moon...
Alright.))

**Comment by camelot-sun** [comment]
> Is camelot-sun your main account?
I don't think you're a freshman on GitHub since you say that you're an iOS developer
sun... moon...
Alright.))

Sorry I don't understand what you are talking about. Yes I am an iOS Developer. This is my main account and this is my first time fully using it and having an account to move my projects. 

My code was previously held privately in my icloud and my team mates private repository (Accurev and Clearcase)

Previously, I came here to read, but I need an acount to move my code.

My asian name is Xiao Jian Sun. But since I am in the US now, I need to have an english name and "Camelot" is the name I chose base on the story of King Arthur. 

Do you have problems with my name?

**Comment by camelot-sun** [comment]
> Well, the story about King Arthur.
You intentionally registered and imitated a user name whose format is similar to mine.
I'm glad that the format of my user name is so welcome and popular here. ╮/(＞▽<)人(>▽＜)╭

Alright.))

OHH. Now I notice your username is almost the same as mine! Well, I am happy that my english name is not weird after all and is use by other too.  @lancelot-moon  cheers!

**Comment by lancelot-moon** [comment]
Хорошо, we together like the story of King Arthur.
Why not reconcile since we're the fans of King Arthur?
Are you a Chinese according to your Asian name?
Simply, welcome here.
We love AdGuard, which is the same.
That's all.

**Comment by camelot-sun** [comment]
Yes. I came from Hong Kong! Thank you! Yes. **Let's work together in the future**. and apologies if I sound harsh. I am just direct. :-)

I think, i am flooding this issue. Apologies again. Let's wait for the AdGuard team's opinion on the matter.

**Comment by ameshkov** [comment]
@camelot-sun is right about action sheets: https://github.com/AdguardTeam/AdguardForiOS/issues/652#issuecomment-364731459

Apple suggests using [action sheets](https://developer.apple.com/ios/human-interface-guidelines/views/action-sheets/) instead of three-button alerts.

Text: `Do you want to reset the statistics along with clearing the log?`
Options:
`Clear log and reset statistics` (red)
`Clear log` (blue)
`Cancel`
