### ISSUE TITLE
New Safari content blockers=Stutter/slowdown?

### ISSUE THREAD

**Issue by mikeoleary7528** [AdguardTeam/AdguardForiOS#662]
Hey Guys,

On the new update iOS beta update 2.0(136) what did you do with the safari filters to make them load again? I noticed a longer load time on loading pages. Didn’t have this before and wanted to make sure I’m not going crazy and tried other safari content blockers and everything loads fine. It’s like a stutter before the pages load. It’s nothing crazy but definitely not like other content blockers or past updates. Anyone else notice this? It’s only after this update where I’ve seen it happen.

**Comment by zznosar** [comment]
@mikeoleary7528 , just tried it and yes, there was a noticeable stutter when you open the page. I thought my internet connection was just cranky... below is the video... probably other testers can check. 

https://vimeo.com/256160905

I enabled AdGuard first, then try to open the page. Seems slow.
I disabled content blocker. Seems fast.
I enabled Better. Seems fast.
I disabled better and enable AdGuard. Seems fast( but i think this is because the AdGuard filters are not completely loaded yet when I opened the page since the facebook and twitter widget are there. It should not be there)

**Comment by mikeoleary7528** [comment]
Okay good just wanted to make sure I’m not going crazy here lol

**Comment by zznosar** [comment]
Yeah! Lol! It’s not crazy slow though. My ipod touch is an old device, so i expect a bit of slowness there.

**Comment by danidoedel** [comment]
Yep can confirm... it‘s much slow!

**Comment by bigdargon** [comment]
Yes! Same issues. After update beta 136, safari load very low :(

**Comment by ameshkov** [comment]
Thank you very much, guys!

We've resolved the issue, expect the fix in the next update.

**Comment by zznosar** [comment]
I think it’s fixed now with beta 137. Can anyone check please? @mikeoleary7528
