### ISSUE TITLE
Feature Request : Add “Find us on” in the About Section

### ISSUE THREAD

**Issue by zeezeepiggy** [AdguardTeam/AdguardForiOS#665]
Is it possible to add a “Find Us on” section in the about? This will then contain the icons of Twitter, Facebook and Instagram where AdGuard can be followed or like. People then can like or follow your page and if there are promotions and contest, they will know.

This will also show that AdGuard team is also active in social media for any quick questions or concern.

 Just a nice to have, I think.

**Comment by planet0** [comment]
This is a good idea, users curious enough to visit the about tab are going to like the ability to support or follow AdGuard on their preferred platform, in just one tap on their device.

Maybe there could be a way to simplify this — have a way to update 'social media' icons on all AdGuard about sections on all apps, as well as the website. Some sort of script or reference point so that when you need to add or remove an icon, change a link, etc, it's all done universally.

The AdGuard website already has the platforms listed, that could be a good start?

<img width="245" alt="image" src="https://user-images.githubusercontent.com/65204836/189121994-785ec2b1-505a-48bd-87fe-1073068ce3a3.png">

**Comment by Versty** [comment]
@zeezeepiggy Links to our socials can be found in Settings tab -> Support -> Discuss
