### ISSUE TITLE
Update the AppStore description with new strings from OneSkyApp

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#679]
Plz carefully update it

**Comment by sergerosenthaler** [comment]
@zebrum @ameshkov please check my comments and translation corrections in the German section (standard and Pro version) on Onesky before you integrate them.

**Comment by sergerosenthaler** [comment]
@zebrum @ameshkov And you should remove this long line and add spaces between the "&". Should look like this "AdGuard - adblock & privacy". I don't know why but this long line and no spaces feels somehow unaesthetic.

![img_0084](https://user-images.githubusercontent.com/25068100/37024900-859db6d2-212a-11e8-8a72-b5a1214a70d8.png)

**Comment by lancelot-moon** [comment]
Translators even moderators don't have the permission to change the title of AdGuard Pro, "AdGuard Pro — adblock&privacy"

Yes, "AdGuard Pro — adblock & privacy" is better.
It seems about a size limit for the app name on oneskyapp.
So AdGuard team used "AdGuard Pro — adblock&privacy".

AdGuard Pro title:
I want to translate it to "AdGuard Pro — 廣告封鎖 & 隱私".
But I don't know if the size will be over the limit of app's title on iTunes app store.
And I don't have the permission to change it.
It's locked by AdGuard team.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/Yvl7IEA.png)
</details><br/>

Free AdGuard title:
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/slp4pm4.png)
</details><br/>

B/R

**Comment by aalpatkina** [comment]
@sergerosenthaler @lancelot-moon 
Unfortunately, we can't add spaces because of the character limit. 
You can translate "AdGuard Pro — adblock&privacy" into your language if you want but you have to keep within the character limit. Otherwise, just copy the English version.

@sergerosenthaler 
Your last translation of description has been approved.

**Comment by sergerosenthaler** [comment]
@aalpatkina please also check the my comments regarding the App tile on OneSky and integrate whatever you think is more logical and cleaner.

**Comment by lancelot-moon** [comment]
@aalpatkina
I knew the character limit for title.
I just answered it to other person for you.

**Comment by sergerosenthaler** [comment]
@aalpatkina yes, but in German "AdGuard Pro - Werbeblocker" for the pro and "AdGuard - Werbeblocker" for the standard version would work from the character limit and this has not been updated on OneSky.

**Comment by aalpatkina** [comment]
@sergerosenthaler 
In my opinion, this title "AdGuard - Werbeblocker & Privatsphärenschutz" is the best one, because it conveys the exact meaning of the original phrase. But unfortunately, we can't change this limit because of the Apple policy. So, I think it would be better to use English version instead of "AdGuard Pro - Werbeblocker" as it doesn't contain the word 'privacy'.

**Comment by sergerosenthaler** [comment]
@aalpatkina makes sense, but please get rid of this LLLLOOONNNG LINE and add the spaces. Is it possible that you update it the German section on OneSky and add a comment, because this was not translated. Thank you!

**Comment by sergerosenthaler** [comment]
@aalpatkina or why not use "AdGuard" for regular and "AdGuard Pro" for the pro version in every language? Would make it clear and streamlined plus you can use it in every language and there is no need to translate this further. And others make this too, e.g. Youtube etc.

**Comment by vbagirov** [comment]
@sergerosenthaler about `—` vs `-`: we use long dash simply because it is grammatically correct. You can google something like "Long dash vs Hyphen" for more details.

It is not required in translations, you can come up with something that doesn't use `—` to fit in the limit.

Also I am not @aalpatkina but we do not "use "AdGuard" for regular and "AdGuard Pro" for the pro version in every language" because of SEO reasons. Gotta use those keywords (in fact, this is why I think "AdGuard Pro — Werbeblocker" is a preferrable phrase for German).

**Comment by sergerosenthaler** [comment]
@vbagirov I agree with you in context of a written publication, but in this case it just looks not right. Or as they describe it on the following website. Nice to have a grammar conversation here. I have to say version 2.0.0 is a nice pice of software, keep it up!

http://www.punctuationmatters.com/hyphen-dash-n-dash-and-m-dash/
Break the rules!

If you are writing formal documents or writing for publication, it’s best to use dashes correctly.
However…  Some people prefer the way a ‘space-en-dash-space’ looks. Sometimes when you use the em-dash people say, “What is that? I don’t like that big long dash thing.” Some technical writers think the n-dash is the only one to use.

It’s not a big deal. I usually use ‘space-n-dash-space’ instead of the m-dash – just to keep everyone happy.  You can see this ‘wrong-n’ method used in countless websites, magazines and papers as a replacement for the m-dash.  If you use the ‘wrong-n’ method and use it consistently, it works fine and seems to keep the greatest number of people happy.

**Comment by sergerosenthaler** [comment]
@vbagirov I think "AdGuard Pro - Werbeblocker" and "AdGuard - Werbeblocker" are perfect and also reflect the wording used on www.adguard.com

**Comment by sergerosenthaler** [comment]
@aalpatkina Please make sure that the App titles for the AppStore description are also up to date. „AdGuard - Werbeblocker“ for the regular and „AdGuard Pro - Werbeblocker“ for the Pro version. And please discuss the dash topic mentored above.

**Comment by aalpatkina** [comment]
@sergerosenthaler our SEO-specialist should check the title by keywords first and then we'll decide what version to use.
Thank you very much!

**Comment by vbagirov** [comment]
As far as I remember these long dashes appeared as a result of SEO-based desicions too. 

From your point it looks more like a matter of preference than anything else, and I don't see a huge reason to change it now. We can just as well receive a complaint from someone else who doesn't like the n-dash. I'm inclined to leave it as it is unless there appears some kind of a SEO-dictated incentive to change it. I don't think it is the biggest problem even if we are mistaken.

**Comment by IvanIin** [comment]
Apple rejected the update of AdGuard for the wrong name in traditional Chinese. The reason is "Your app name to be displayed on the App Store includes keywords or descriptors, which are not appropriate for use in an app name.". I returned the English app name for simplified and traditional Chinese. We need a simpler name in these languages that does not contain keywords.

**Comment by zebrum** [comment]
fixed in onesky
