### ISSUE TITLE
Enable autoupdate over Wi-Fi only by default

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#682]
Also, make sure that it works for everything:

1. Safari filters updates
2. Privacy subscriptions updates

**Comment by lancelot-moon** [comment]
Before I did the request, https://github.com/AdguardTeam/AdguardForiOS/issues/663, I ever thought if I should do this request for letting "Auto Update over Wi-Fi only" include the updates of subscriptions.

But I cancelled my thought.
Because users need to manually click "Check for updates", it represents that users have made the decision to update via Wi-Fi or cellular network.

It's still a good idea which lets "Auto Update over Wi-Fi only" include the updates of subscriptions.
Then we only need to add the headline, "For SAFARI CONTENT BLOCKING", and divisional lines for "Use Simplified Filters" and "Invert Whitelist" in Advanced Settings.

B/R

**Comment by lancelot-moon** [comment]
Honestly, if you let "Auto Update over Wi-Fi only" include not only Safari filters but also Privacy Settings' subscriptions........

Why do you not let AdGuard Pro automatically update Safari filters & Privacy Settings' subscriptions in the background via cellular network / Wi-Fi by default?

This is much better than enabling"Auto Update over Wi-Fi only" by default.
In the past, I supposed that you give up auto updates for Safari filters & Privacy Settings' subscriptions due to Apple's policy.

**Comment by ameshkov** [comment]
This is a good idea, @zebrum plz take care of it & create a new task here on GH.

> Original: "If this setting is enabled, AdGuard will only use WiFi for background filter updates."
> New: "On top of manually updating Safari filters & Privacy Settings' subscriptions via cellular network / Wi-Fi, if this setting is enabled, AdGuard will only use Wi-Fi for their auto updates in the background."
