### ISSUE TITLE
Please add Cloudflare Public DNS and others in the known DNS list.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#737]
Cloudflare Public DNS:
https://1.1.1.1/

Global Coverage From an Anycast-Powered Network
https://www.cloudflare.com/dns/
https://blog.cloudflare.com/announcing-1111/

IPv4:
one.cloudflare-dns.com 1.1.1.1
two.cloudflare-dns.com 1.0.0.1

IPv6:
2606:4700:4700::1111
2606:4700:4700::1001

It supports both DNS-over-TLS and DNS-over-HTTPS.

DNS speed test:
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/R2SGQ5b.png)
</details><br/>

(FUN DNS, OneDNS, PdoMo-DNS, AdClear DNS and CuteDNS are DNS providers with adblock feature from China.
But I don't trust them.)

DNS Performance Analytics and Comparison:
https://www.dnsperf.com/#!dns-resolvers

How to Pick the Best Threat-blocking DNS Provider (Updated):
https://goo.gl/jqEtVD

SafeSurfer:
http://www.safesurfer.co.nz/
104.155.237.225
104.197.28.121

Norton ConnectSafe:
(It's in the known DNS servers list of AdGuard for Android, but AdGuard Pro for iOS doesn't have it. )
https://dns.norton.com/configureRouter.html
199.85.126.10
199.85.127.10

Strongarm:
https://strongarm.io/
54.174.40.213
52.3.100.184

Freenom World DNS:
http://www.freenom.world/en/index.html
80.80.80.80
80.80.81.81

Fourth Estate:
https://dns.fourthestate.co/
45.32.36.36
45.77.165.194
179.43.139.226

SprintLink DNS:
https://www.sprint.net/index.php?p=faq_dns
NS3-ASIA.SPRINTLINK.NET | 203.222.38.130 | Asia
NS2-ASIA.SPRINTLINK.NET | 203.222.36.130 | Asia
NS1-ASIA.SPRINTLINK.NET | 203.222.32.130 | Asia

Neustar Recursive DNS:
https://www.security.neustar/dns-services/free-recursive-dns-service
156.154.70.2
156.154.71.2

SafeDNS:
https://www.safedns.com/en/features/
195.46.39.39
195.46.39.40

Alternate DNS:
https://alternate-dns.com/index.php
23.253.163.53
198.101.242.72

Hurricane Electric:
http://www.he.net/
74.82.42.42

Fortinet Secure DNS: (malware/phishing/malvertising/botnet blocking)
http://cookbook.fortinet.com/dns-web-filtering/
208.91.112.53
208.91.112.52
208.91.112.220
80.85.69.54

(dns-server:208.91.112.53:53 tz=0 req=919160 to=545900 res=117880 rt=1800 secure=0 ready=1
dns-server:208.91.112.52:53 tz=0 req=913029 to=520111 res=134810 rt=6 secure=0 ready=1
dns-server:208.91.112.220:53 tz=-480 req=0 to=0 res=0 rt=0 secure=1 ready=1
dns-server:80.85.69.54:53 tz=0 req=0 to=0 res=0 rt=0 secure=1 ready=1
vfid=0, interface=wan1, ifindex=6, recursive, dns)

FreeDNS:
https://freedns.zone/en/
37.235.1.174
37.235.1.177

Smart DNS Proxy:
https://www.smartdnsproxy.com/Servers?location=sg

I also suggest that AdGuard DNS uses Cloudflare Anycast-Powered Network instead of vultr.com if it's possible...
https://github.com/AdguardTeam/AdguardDNS/issues/261

Thanks.

**Comment by kathampy** [comment]
This requires DNS over HTTPS support. AdGuard for iOS currently only allows DNSCrypt servers to be added.

**Comment by lancelot-moon** [comment]
Cloudflare Public DNS can be temporarily put in general DNS list, such as Quad9 DNS.
Its speed is fast as Google DNS in my country.

In the future, maybe AdGuard will not use DNSCrypt, and then support DoH or DoT for encrypting DNS.

If it's possible, hope AdGuard DNS uses its anycast network.

**Comment by XantherBanter** [comment]
@X8716e 

I wanna say some few things about your statement. I do understand your paranoia and applaud you for taking proactive steps in maintaining your privacy over the internet although I am am not sure why you surmise that a security company that provided protection to websites against DDOS attacks and bots with a great track record on privacy does this free DNS service to collect data and sell it to other entities. The way I see it, it’s a PR stunt for them to show off their capablities and rack up more customers in the process. A win-win for all.

Probably because of that Cambridge Analytica incident.

Honestly, that’s understandable. But if you tried to curb that paranoia for a second and try to search on the [DNS’ privacy policy](https://developers.cloudflare.com/1.1.1.1/commitment-to-privacy/privacy-policy/privacy-policy/) (which is short but concise) and [APNIC’s Announcement](https://labs.apnic.net/?p=1127) along with customer testimonials, news, company’s privacy policies, etc.,  you can judge if their services and ventures are trustworthy or not. For me, reading these pages and I could say that I trust 1.1.1.1.

That’s all. Have a good day.

**Comment by X8716e** [comment]
@XantherBanter ,

I understand your naivety regarding the promises of corporate entities, as well as your glossing over of the very statement you link to, although I cannot understand what DDoS protection services has to do with privacy. So let’s leave that out of the equation. The very fact that they log information is itself a privacy violation, period. This enables them to do exactly what they say do - both store certain record types indefinitely as well as allow law enforcement agencies full access to their logs, and let’s be honest here, information can never be fully anonymised, no matter what is claimed. Nor can logs truly be deleted as the most basic of forensics can recover deleted records with ease. So I shall stick with specific @OpenNIC servers, those of @luggs as I trust him & know that he does no logging and therefore has nothing to turn over to anyone or use for anything. Again, I understand your naivety in these matters. You have a good day as well.

**Comment by luggs-co** [comment]
😊  awww, you guys!

**Comment by XantherBanter** [comment]
@X8716e 

1. Calling me naive when OpenNIC, the DNS you’re using right now, also log information, from DNS record queries to the basic troubleshooting logs and they have no official policy on how the server owners handle these logs in terms of retention and privacy. So that’s a privacy violation too right? Even if you trust your DNS provider, your ISP has the power to see and log your usage, the sites you visit, etc.

Digressing for a second, This app, Adguard, also collect logs and sends it to their servers for their purposes. The mobile device you’re using, assuming an iOS Device, collects logs. This site, collects logs too. And if you’re paranoid, you can surmise that all of these companies can send to authorities, governments, you name it.

I’m not saying all apps sell their collected info to people so you better log off the internet forever (that’s pretty extreme case if I follow your train of thought) All I’m saying is that it is impossible that no one logs something about you and your usage. All it takes is to do a little research and look at their privacy policies, how they handle your data and their track record and judge if they can be trusted, whether is a big company or even one guy handling a DNS server. The same way you probably  did when you used lugg’s servers, you trust that guy that it implements OpenNIC reliably and does what it say that he does not log. I bet you did your research and came up to that conclusion.

2. I could bet right now that any company or any government agencies cannot guarantee that they could not recover a file, let alone retrieve fingerprints from it, that has been deleted using a 3 pass DoM standard (this is considered overkill in today standards) in a SSD or even Even 1 pass pseudorandom data overpass is sufficient enough for the file to be unrecoverable. You just can’t.

I applaud your naivety in these matters. This will be my last response.

**Comment by X8716e** [comment]
I do what I can when I can. I refuse to allow everyone to commit violations of privacy when it is avoidable. Each member of @opennic has varying policies regarding logging. This is why I use @luggs-co’s servers. No logging. Period. I’ve been a member of @opennic for many years & have become familiar with other members. So it’s not a research based decision as much as a peer based, fully informed decision. It’s funny how you are so offended by the label of naivety when you had absolutely no problem in calling me paranoid. As to your example regarding deletion of information using military-based standards is unrelated to what is used by companies such as your beloved cloudfare, using it to prove a point already well-known is pure sophistry. Perhaps try not to sling names around at people from the very start unless you’re prepared for it to bite you in the rear.

**Comment by X8716e** [comment]
@lancelot-moon ,
The addition of a direct link to the information regarding Cloudfare’s partnership with Baidu would be of great help to many of us who do not live in China. It’s quite informative regarding Cloudfare’s attempt to ultimately serve China _and_ remain (relatively) outside of govermental controls via an upcoming change in encryption architecture.

**Comment by IvanIin** [comment]
@balupton we use dnscrypt 1 which does not support DoH. Dnscrypt 2 is completely different product.

**Comment by ameshkov** [comment]
There is a task about integrating with dnscrypt v2 already: #585

**Comment by lancelot-moon** [comment]
Please add this. too.
https://101.101.101.101/index_en.html
Quad101 is TWNIC's experimental Public DNS project. TWNIC (Taiwan Network Information Center) is a ccTLD (country-code Top Level Domain) registry operator. TWNIC runs one of the world's fastest DNS infrastructure.
The specific IP address (101.101.101.101) has been assigned to Quad101 Public DNS systems. TWNIC's world-class network infrastructure along with comprehensive Quad101 features will build a better Internet in Taiwan.

Quad101 DNS
IPv4:
101.101.101.101
101.102.103.104

IPv6:
2001:de4::101
2001:de4::102

**Comment by lancelot-moon** [comment]
https://blahdns.com/

BlahDNS started to support DoH/DoT.

**Comment by ameshkov** [comment]
https://adguard.com/en/blog/adguard-pro-discontinued/

**Comment by LewisLebentz** [comment]
Is it better to use Cloudflare's DNS with Anycast or without in Custom DNS?
