### ISSUE TITLE
DNS-over-HTTPS / DNS-over-TLS support

### ISSUE THREAD

**Issue by kathampy** [AdguardTeam/AdguardForiOS#738]
Cloudflare's new public resolver (1.1.1.1) only supports DNS-over-HTTPS and DNS-over-TLS. I understand that once you integrate with DNSCrypt-proxy v2, supporting DNS-over-HTTPS will be technically possible. If so, please expose the functionality in the UI as well so we can add custom DNS-over-HTTPS servers.

**Comment by lancelot-moon** [comment]
XDD
The same opinion with mine.
The speed of DNSCrypt servers is slow, which lets me not want to use it.

Google DNS supports DoH.
Cloudflare DNS supports both DoH and  DoT.
They're excellent DNS providers which give fast resolvers.
Why did AdGuard team choose DNSCrypt?

**Comment by zznosar** [comment]
Probably because DNSCrypt was created first and has been there for a while than DNS over TLS was created? Before AdGuard for iOS introduced DNSCrypt, it’s already applied in their DNS since 2016. And is used by the PC client of DNScrypt. DNSCrypt v2 should support the above request. I believe DNSCrypt started it all. It’s just that it was not standardized. My company uses DNSCrypt...

**Comment by X8716e** [comment]
Refer to my response @ https://github.com/AdguardTeam/AdguardForiOS/issues/737.

**Comment by lancelot-moon** [comment]
DNSCloak • DNSCrypt DoH client
https://itunes.apple.com/us/app/dnscloak-dnscrypt-doh-client/id1330471557?mt=8

That app supports both DNSCrypt and DoH.

But adblock feature may be invalid in some situation with encrypted DNS, which is what needs to be noted.

**Comment by X8716e** [comment]
The app to which you refer, @lancelot-moon, is also **not** open source. That alone is reason not to use it.

**Comment by ameshkov** [comment]
https://adguard.com/en/blog/adguard-pro-discontinued/
