### ISSUE TITLE
After shifting from Split-Tunnel mode to Full-Tunnel mode & using DNSCrypt AdGuard DNS and then enable AG Pro Protection (frequently do the steps), VPN connection in iOS Setting isn't established.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#742]
I read this. https://github.com/AdguardTeam/AdguardForiOS/issues/740#issuecomment-379186409
> And in split mode, ios switches to system dns for 1 minute.

So I go to try if there are other bugs when shifting from Split-Tunnel mode to Full-Tunnel mode & using DNSCrypt AdGuard DNS.

After shifting from Split-Tunnel mode to Full-Tunnel mode & using DNSCrypt AdGuard DNS and then enable AG Pro Protection (frequently do the steps), VPN connection in iOS Setting isn't established.

Please see the video:
https://youtu.be/Ymdco6iDI2Q

I already sent the bug report to AdGuard Support at 18:19 on 6th April (GMT+8).
User ID: 1425202
Subject: [AdGuard Pro for iOS] bug report

Update:
In such situation, let AdGuard Pro run in the background and then wait for some time.
Afterwards, open AdGuard Pro again.
VPN connection will be established.

B/R

**Comment by camelot-sun** [comment]
As a normal user, i will not perform the above step. This is just nit picking. I think it’s a joke.

The reason why its like this is because of your frequent changes on the setting.

Think about it as your router. If you on, off, on, off your router, you will not have internet until it establishes the connection. The same applies with the above.

A prior process needs to be executed and completed first before another action takes place.

This is a normal computing and software behavior. Even desktop applications will behave like this...

I dont think this is bug. Try other VPN. If you on off, on off, it will behave as the above.

You mentioned that after you waited for a minute, it establishes the connection, of course, because the initialization and prior processes are completed.

**Comment by lancelot-moon** [comment]
Even if not frequently doing the steps, I also successfully reproduced the issue.
The problem of probability.

Reproduction steps:
1. Enable AdGuard Pro Protection with Split-Tunnel mode and general AdGuard DNS.
2. Turn off AdGuard Pro Protection.
3. After shifting from Split-Tunnel mode to Full-Tunnel mode & choosing DNSCrypt AdGuard DNS, check if VPN connection in iOS Setting is established or not.
4. Repeat step 3 if VPN connection in iOS Setting is established.
(You can wait for some time and then repeat step 3.
Don't need to frequently do.)
5. There is the probability: VPN connection in iOS Setting isn't established even if the status of AG Pro Protection shows"enabled" in AG Pro app.

Anyway, simply try.
You'll get it.

**Comment by zebrum** [comment]
let's have one issue #744
