### ISSUE TITLE
After shifting from Split-Tunnel mode to Full-Tunnel mode & using DNSCrypt AdGuard DNS and then successfully enable AG Pro Protection (there is Wi-Fi icon), it seems that it will lose internet connection for some time.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#743]
After shifting from Split-Tunnel mode to Full-Tunnel mode & using DNSCrypt AdGuard DNS and then successfully enable AG Pro Protection (there is Wi-Fi icon), it seems that it will lose internet connection for some time (DNS maybe didn't normally work at that time).

A newspaper app will crash.
The newspaper app:
https://tinyurl.com/y9vb86t5

Mobile BBS app is unable to establish connection.
Unable to visit websites by Safari and so on.

Please see the video:
https://youtu.be/nIxJVQJnxkg

Wi-Fi
iPhone 6 Plus & iOS v11.3
AG Pro v2.0.2(146)

Reproduction steps:
1. Enable AdGuard Pro Protection with Split-Tunnel mode and general AdGuard DNS.
2. Turn off AdGuard Pro Protection.
3. After shifting from Split-Tunnel mode to Full-Tunnel mode & choosing DNSCrypt AdGuard DNS, AdGuard Pro Protection is enabled.
4. Open any other apps.
In my case, I open a newspaper app, mobile BBS app and Safari.
They are unable to establish internet connection, even the newspaper app will crash.

I already sent the bug report to AdGuard Support at 19:05 on 6th April (GMT+8).
User ID: 1425202
Subject: [AdGuard Pro for iOS] bug report

In such situation, constantly try more apps for some time.
Finally, apps can connect to internet.

B/R

**Comment by camelot-sun** [comment]
As a normal user, i will not perform the above step. This is just nit picking. I think it’s a joke.

The reason why its like this is because of your frequent changes on the setting.

Think about it as your router. If you on, off, on, off your router, you will not have internet until it establishes the connection. The same applies with the above.

A prior process needs to be executed and completed first before another action takes place.

This is a normal computing and software behavior. Even desktop applications will behave like this...

I dont think this is bug. Try other VPN. If you on off, on off, it will behave as the above.

You mentioned that after you waited for a minute, it establishes the connection, of course, because the initialization and prior processes are completed.

**Comment by zebrum** [comment]
let's have one issue #744

**Comment by lancelot-moon** [comment]
> As a normal user, i will not perform the above step. This is just nit picking. I think it’s a joke.
The reason why its like this is because of your frequent changes on the setting.

A joke?
You are also a bit disrespectful to me.

For the test, there is no frequent change on the setting.
Even if it's just a problem of probability in my another issue, https://github.com/AdguardTeam/AdguardForiOS/issues/742#issuecomment-379232926.

About a router, do you know it would generally twinkle red light until it established internet connection with green light?

I tried other real VPN and never met the issue.
Usually, real VPN app take more time for establishing connection.

Why do we talk about a router?
Well, we talk about setup time.
Compared with general DNS, if needing more setup time when setting DNSCrypt DNS, a designer doesn't give enough setup time in his design, which is also a bug.
Do you understand?
I trust AdGuard team can solve the issue.

I won't reply anymore under this topic.
