### ISSUE TITLE
errors when tunnel starts with encrypted DNS

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForiOS#744]
#740 #742 #743 

User ID: 1425202

**Comment by lancelot-moon** [comment]
Split-Tunnel mode starts with encrypted DNS:
https://github.com/AdguardTeam/AdguardForiOS/issues/740

**From Split-Tunnel mode to Full-Tunnel mode** and then start with encrypted DNS:
https://github.com/AdguardTeam/AdguardForiOS/issues/742
https://github.com/AdguardTeam/AdguardForiOS/issues/743

There is no such issue with general DNS.

**Comment by lancelot-moon** [comment]
These issues aren’t solve in beta v2.10(149).

**Comment by IvanIin** [comment]
@lancelot-moon can you send logs?

**Comment by lancelot-moon** [comment]
I just sent the bug report to AdGuard Support at 18:46 on 12th April (GMT+8).
User ID: 1425202
Subject: [AdGuard Pro for iOS] bug report

I only sent the bug report for invalid adblock with split-Tunnel mode and encrypted DNS.

From Split-Tunnel mode (ever enabled) to Full-Tunnel mode and then start with encrypted DNS.
https://github.com/AdguardTeam/AdguardForiOS/issues/743
It's also not solved.
Do I need to send the bug report about it again although there is no difference, compared with before?

**Comment by lancelot-moon** [comment]
@ameshkov 
@IvanIin 

Thanks, Ivanlin.
You prove that they're bugs, not jokes.
AG Pro beta v2.1.0(151) does great work for VPN connection.

Only https://github.com/AdguardTeam/AdguardForiOS/issues/742#issuecomment-379232926 isn't solved.
I had enabled AG Pro VPN in app, but VPN status in iOS setting was still off.
Is it due to unstable Full-Tunnel mode (no VPN icon)?
In such situation, when I run some apps which do internet connection, VPN status would be automatically from "off" to "on".

It seems that https://github.com/AdguardTeam/AdguardForiOS/issues/740, https://github.com/AdguardTeam/AdguardForiOS/issues/743 and https://github.com/AdguardTeam/AdguardForiOS/issues/752 are solved.

The issues of AG Pro VPN connection really torment AdGuard's iOS users.
I think that you can release hotfix update on App Store if you don't plan to do more other enhance in v2.1.0.

Another thing:
Do you want to modify the title and description of AG (Pro) for iOS on App Store?
It's because I saw changes on oneskyapp.
Just check with you.

Future plans about my other suggests on GitHub:
a. DNScrypt v2
Maybe you also need to update encrypted DNS list in AG Pro for iOS.
https://github.com/AdguardTeam/AdguardForAndroid/issues/1831
b. DoH/DoT support (encrypted Google DNS and Cloudflare DNS)
c. Add separate switches to turn on and off blacklist, whitelist, each subscription and Safari's filters, user filter & whitelist.
d. Checkbox for enabling/disabling rules in Safari's user filter & whitelist and Privacy settings' user rules (blacklist & whitelist).
e. Show the sum of current active rules (user rules + subscriptions) on the top of Privacy Settings, which is convenient for users.
f. Let a tap for enabling or disabling DNS requests log back. (Pause the logging.)
g. Ability to edit subscription profile.
h. Please give max size of 20 custom DNS servers in DNS setting from AG Pro v2.0.0. & Improve the layout in DNS setting.
i. Please add Cloudflare Public DNS and others in the known DNS list.
j. Please change the arrangement of tutorial videos from vertical stack to overlapping on the main screen.
It's about aesthetics of app's interface on the main screen.
The scene of tutorial video is fashionable and modern to the sense of sight.
Such like a beautiful banner there.
However, it'll give different feeling on main screen with different arrangement.
Vertical stack of the videos: inharmonious
Overlapping the videos: harmonious
Hiding all videos: ugly

B/R

**Comment by lancelot-moon** [comment]
Hi, I have tried AG Pro beta v2.1.0(152).

It seems that https://github.com/AdguardTeam/AdguardForiOS/issues/742#issuecomment-379232926 is also solved.

From AG Pro v1.0~v2.0, unstable VPN tunnel is the most obvious shortcoming for AdGuard Pro for iOS.
However, AG Pro beta v2.1.0(151/152) deeply surprises me.
You really did hard work in VPN tunnel this time!
Thank you very much!

**Comment by lancelot-moon** [comment]
@IvanIin

Hi,

What did you change in AG Pro beta v2.1.0(153)?
Originally, ad blocking worked.

After I operated between different VPN tunnel mode and general/encrypted DNS, ad blocking became invalid.
Even I tried to reboot iphone or downgrade to v2.1.0(152), which is useless.

I already sent the bug report to AdGuard Support at 09:36 on 27th April (GMT+8).
User ID: 1425202
Subject: [AdGuard Pro for iOS] bug report
