### ISSUE TITLE
Manually adding/removing URLs to blacklist disables filtering

### ISSUE THREAD

**Issue by kevandoyle2** [AdguardTeam/AdguardForiOS#776]
So far, I've noticed that this only happens while using an encrypted DNS.

### Steps to reproduce

While using an encrypted DNS:

1. Click on a URL in the requests log and add it to/remove it from the blacklist. 
2. The VPN icon will disappear, and even though the buttons in AG and in iOS settings show it is on, it will no longer filter DNS requests.
3. Sometimes, the VPN in iOS will disable itself as well, and must be manually re-enabled to get it working again.

### Expected behavior
The filtering module should remain connected when modifying blacklist entries and in changing DNS.

### Actual behavior
Filtering is disabled, and sometimes the VPN module in iOS is toggled off as well.

In general, making modifications to AG settings while connected to encrypted DNS is unreliable in terms of a stable connection.

### Customer ID 
1860764

### Your environment
* Device model and storage size: iPhone 8 64gb
* Operating system and version: 11.3.1
* Wi-fi or mobile internet connection: BOTH

**Comment by X8716e** [comment]
I’ve found that for now the best way around the issue is to manually disconnect PRIVACY > Status from within AdGuard immediately prior to adding or removing any domains to/from the blacklist. Then just reconnect in the same way after finishing. Wait for a moment to ensure your connection by waiting a few seconds for the DNS count to go up a bit. If you want to be extra-thorough, look at the DNS log to ensure those connections are actually being made. It’s not permanent solution, but it works and barely adds to the time spent adjusting your manual blacklist.

**Comment by zebrum** [comment]
@IvanIin take a look please
we have at least 2 complaints about this.

**Comment by ffooffer** [comment]
Neic
