### ISSUE TITLE
Need help please

### ISSUE THREAD

**Issue by jostikeros** [AdguardTeam/AdguardForiOS#805]
I just bought adguard pro for my iphone, and I want to block this url: deezer.com/track/-2511222922 exactly that url the problem is. than putting it on blocked hosts. lock deezer.com but the whole page in general and I do not want that. I only want to block that url, but not the whole page. what I need to block is for the application, not for the safari browser. Thank you

**Comment by Eugene-Savenko** [comment]
@jostikeros this is one of the drawbacks of DNS / hosts-based ad blocking, it's rough and will block you the whole domain instead of a particular URL.

**Comment by lancelot-moon** [comment]
That's why there is risk if using filters for HTTPS filtering in subscriptions.
AdGuard Pro only supports basic adblock rule syntax, hosts file and domain format for subscriptions.
For system-wide ad blocking, AdGuard Pro for iOS only does DNS filtering and is unable to block particular full URL path.
AdGuard for Android can do HTTPS filtering for system-wide ad blocking, but AdGuard Pro for iOS can't do, understand?
