### ISSUE TITLE
Please give proxy settings.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#832]
Hi, may you add proxy settings?
Support Socks4/5, HTTP, HTTPS, SSH, ShadowSocks, Socks over TLS and so on.

I want to connect to myself proxy server by fake VPN.

Especially, AG (Pro) for iOS has no proxy settings, which troubles me.
May AdGuard team early give proxy settings on regular AG for iOS or maybe another new iOS app (AdGuard Home for iOS)?

Thanks.

**Comment by SiNaPsEr0x** [comment]
Idem request... thanks

**Comment by Andjustsoso** [comment]
The proxy is very useful, because current version's vpn can't work with the third party proxy.
And I am very disappointed with Adguard Pro, I think I waste my money to buy it

**Comment by kathampy** [comment]
This is a complicated problem because if a proxy is configured in the Wi-Fi settings, applications directly make HTTP GET / CONNECT requests with the desired hostname and do not perform a DNS lookup. The DNS lookup is performed on the proxy server.

AdGuard must run a local proxy server, intercept the hostname from the connection, and then either reject the connection if the hostname is blacklisted or forward it to the real proxy server.

**Comment by ameshkov** [comment]
This won't be possible on iOS at least for us. Apple is very reluctant about our new features.

**Comment by lancelot-moon** [comment]
@ameshkov 
There are many proxy apps on app store.
Why is it impossible?

> Apple is very reluctant about our new features.
I guess you meant system-wide blocking.
But proxy function and system-wide blocking are different things.
Hope you can consider again.
AdBlock by FutureMind was also updated recently.
Apple should be not reluctant...
