### ISSUE TITLE
AdGuard Pro not blocking ads in Chrome 

### ISSUE THREAD

**Issue by srikat** [AdguardTeam/AdguardForiOS#835]
Hi,

I am using AdGuard Pro on iOS (iPhone X) and trying to figure out how to get it working on Chrome app. It works fine in Safari.

Any ideas or suggestions for a working alternative?

**Comment by zebrum** [comment]
What DNS server have you chosen in DNS settings in AdGuard app?

**Comment by lancelot-moon** [comment]
AdGuard Pro works fine in Safari because it provides a content blocker to Safari.
Chrome app doesn't have the function of content blocker.
You should contact with Google.

Network-wide HTTPS filtering through yourself proxy server which is filtered by AdGuard for Windows/macOS.
Or simply give up Chrome app on iOS, which is easier.

**Comment by srikat** [comment]
>What DNS server have you chosen in DNS settings in AdGuard app?

AdGuard DNS Family Protection (IPv6)

**Comment by karina-archazh** [comment]
@srikat Hi,

could you please clarify what is your mobile operator?
Also please try to re-connect your DNS settings to IPv4.

**Comment by alexchandel** [comment]
@zebrum The App Store version of this doesn't block ads in Chrome anymore, right?  I need to compile & side-load this app now, right?  Are there any code changes I need to make to get it to work for Chrome now?

**Comment by zebrum** [comment]
@alexchandel AdGuard Pro from app store is working, nothing has changed.
