### ISSUE TITLE
Filters updates issue.

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForiOS#85]
filter updates fails with a message "You should delete your whitelist and/or personal filter list."
Turning English filter off fixes it.

Also, some filters show "last updated" time in future, probably a timezone issue.

please refer to ZDX-733-22529 for logs

**Comment by Stillness-2** [comment]
About "last updated".
There is an opinion, that is time did not synced on the back-end server.

**Comment by vozersky** [comment]
same here: TICKET ID PAF-836-50942

"everytime i need to update. I also need to delete the app and reloaded all the filter. Otherwise it won't work"

**Comment by ameshkov** [comment]
This is a ticket from the guy in Twitter. Should be good now.

**Comment by vozersky** [comment]
The twitter guy's ticket was RMR-152-60966, no?

**Comment by maciboy** [comment]
Hey, i'm the one how issued ZDX-733...

I don't know if there were any changes at the backend yet, however, after several deletions and reconfiguration of subscribed filters, the issue is gone temporarily on both my originally mentioned devices.
Some time in between the German filter list caused the described issue, so it seems as if the English filter is/was not the main initiator of the issue...

Will update here, if the issue appears again.

Thanks for your work so far!
If you have any further questions, don't hesitate to ask ;)

**Comment by evgeniy-ADG** [comment]
Another complaint here: TXZ-582-42578
![image](https://cloud.githubusercontent.com/assets/15856304/15259776/eaa262b8-195b-11e6-9db7-64964046f17c.png)

**Comment by evgeniy-ADG** [comment]
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/16362387/591bb6fa-3bb6-11e6-836b-df447806beb5.png)
</details>
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.87.47 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.45 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.10.44 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.71 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.60.79 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.60.47 Enabled=YES

User #1153042

**Comment by ameshkov** [comment]
@evgeniy-ADG what's your question?

**Comment by evgeniy-ADG** [comment]
it's under the first spoiler, it's regarding the issue. he has only 7 filters enabled
users' do not understand what to do in such cases. maybe you could add some specific description or a manual...

**Comment by ameshkov** [comment]
The easiest way to fix this is to turn off some filter.
