### ISSUE TITLE
Update DNScrypt to V2

### ISSUE THREAD

**Issue by zznosar** [AdguardTeam/AdguardForiOS#883]
Hi All,

Since apple restricted the use of VPN functionality in ios, can we atleast update the DNSCrypt Functionality to v2? DNSCloak was able to provide an update with its app and 1.1.1.1 app was also introduced too and was ok with apple.

We can remove the host file functionality, but i believe apple will allow the DNSCrypt functionality in the app.

**Comment by ameshkov** [comment]
Sorry for that it takes soooo long to update the AG app. This "it's done when it's ready" mentality of us has some drawbacks:(

To the original question - we won't be using `dnscrypt-proxy` anymore in the future versions of AG (both Android and iOS). The problem with it is that it's a bit too heavy, and most of its functions are simply not used (because they're for server-side).

We intend to use our own lightweight implementation that will support all the protocols we need including DoH, DoT, and DNSCrypt.
